
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


 
/**
 * 条件比较操作符
 */
export enum ConditionOperatorType {
    /**
     * &lt;
     */
    Less = 0,
    /**
     * &gt;
     */
    Greater = 1,
    /**
     * &lt;=
     */
    LessEqual = 2,
    /**
     * &gt;=
     */
    GreaterEqual = 3,
    /**
     * 等于
     */
    Equal = 4,
    /**
     * !=
     */
    NotEqual = 5,
}

 
 
/**
 * 条件数据源
 */
export enum ConditionType {
    /**
     * param=itemId
     */
    ItemCount = 1,
    /**
     * param=itemId
     */
    GatherCount = 2,
    /**
     * 累计锄地
     */
    TillCount = 3,
    /**
     * 累计播种
     */
    PlantCount = 4,
    /**
     * 累计浇水
     */
    WaterCount = 5,
    /**
     * 累计收获
     */
    HarvestCount = 6,
    /**
     * param=recipeId
     */
    CraftCount = 7,
    /**
     * 累计钓鱼
     */
    FishCount = 8,
    /**
     * 金币数量
     */
    Gold = 9,
    /**
     * 剧情旗标次数 param=flagId
     */
    Flag = 10,
}

 
 
/**
 * 引导动作
 */
export enum GotoAction {
    /**
     * 无动作
     */
    None = 0,
    /**
     * 打开工作台
     */
    OpenCraft = 1,
    /**
     * 选中锄头
     */
    SelectHoe = 2,
    /**
     * 选中种子
     */
    SelectSeeds = 3,
    /**
     * 选中水壶
     */
    SelectCan = 4,
    /**
     * 选中手
     */
    SelectHand = 5,
    /**
     * 选中鱼竿
     */
    SelectRod = 6,
    /**
     * 打开背包
     */
    OpenBag = 7,
    /**
     * 提示农田
     */
    HintFarm = 8,
    /**
     * 提示杂草
     */
    HintGrass = 9,
    /**
     * 提示钓鱼
     */
    HintFish = 10,
    /**
     * 提示工作台
     */
    HintCraft = 11,
    /**
     * 提示紫晶陨石
     */
    HintMeteor = 12,
    /**
     * 提示通往小镇的路牌
     */
    HintTownGate = 13,
    /**
     * 提示镇长府
     */
    HintMayor = 14,
}

 





export class CCondition {

    constructor(_json_: any) {
        if (_json_.id === undefined) { throw new Error() }
        this.id = _json_.id
        if (_json_.type === undefined) { throw new Error() }
        this.type = _json_.type
        if (_json_.compare_mode === undefined) { throw new Error() }
        this.compareMode = _json_.compare_mode
        if (_json_.desc === undefined) { throw new Error() }
        this.desc = _json_.desc
        if (_json_.goto_id === undefined) { throw new Error() }
        this.gotoId = _json_.goto_id
    }

    readonly id: number
    readonly type: ConditionType
    readonly compareMode: ConditionOperatorType
    readonly desc: string
    readonly gotoId: number

    resolve(tables:Tables) {
        
        
        
        
        
    }
}





export class CCraftCost {

    constructor(_json_: any) {
        if (_json_.id === undefined) { throw new Error() }
        this.id = _json_.id
        if (_json_.recipe_id === undefined) { throw new Error() }
        this.recipeId = _json_.recipe_id
        if (_json_.item_id === undefined) { throw new Error() }
        this.itemId = _json_.item_id
        if (_json_.count === undefined) { throw new Error() }
        this.count = _json_.count
    }

    readonly id: number
    readonly recipeId: string
    readonly itemId: string
    readonly count: number

    resolve(tables:Tables) {
        
        
        
        
    }
}





export class CCraftRecipe {

    constructor(_json_: any) {
        if (_json_.id === undefined) { throw new Error() }
        this.id = _json_.id
        if (_json_.name === undefined) { throw new Error() }
        this.name = _json_.name
        if (_json_.desc === undefined) { throw new Error() }
        this.desc = _json_.desc
        if (_json_.out_item === undefined) { throw new Error() }
        this.outItem = _json_.out_item
        if (_json_.out_count === undefined) { throw new Error() }
        this.outCount = _json_.out_count
        if (_json_.craft_seconds === undefined) { throw new Error() }
        this.craftSeconds = _json_.craft_seconds
        if (_json_.sort === undefined) { throw new Error() }
        this.sort = _json_.sort
    }

    readonly id: string
    readonly name: string
    readonly desc: string
    readonly outItem: string
    readonly outCount: number
    readonly craftSeconds: number
    readonly sort: number

    resolve(tables:Tables) {
        
        
        
        
        
        
        
    }
}





export class CGoto {

    constructor(_json_: any) {
        if (_json_.id === undefined) { throw new Error() }
        this.id = _json_.id
        if (_json_.action === undefined) { throw new Error() }
        this.action = _json_.action
        if (_json_.hint === undefined) { throw new Error() }
        this.hint = _json_.hint
    }

    readonly id: number
    readonly action: GotoAction
    readonly hint: string

    resolve(tables:Tables) {
        
        
        
    }
}





export class CQuest {

    constructor(_json_: any) {
        if (_json_.id === undefined) { throw new Error() }
        this.id = _json_.id
        if (_json_.name === undefined) { throw new Error() }
        this.name = _json_.name
        if (_json_.desc === undefined) { throw new Error() }
        this.desc = _json_.desc
        if (_json_.condition_id === undefined) { throw new Error() }
        this.conditionId = _json_.condition_id
        if (_json_.param === undefined) { throw new Error() }
        this.param = _json_.param
        if (_json_.num === undefined) { throw new Error() }
        this.num = _json_.num
        if (_json_.goto_id === undefined) { throw new Error() }
        this.gotoId = _json_.goto_id
        if (_json_.reward_gold === undefined) { throw new Error() }
        this.rewardGold = _json_.reward_gold
        if (_json_.reward_item === undefined) { throw new Error() }
        this.rewardItem = _json_.reward_item
        if (_json_.reward_count === undefined) { throw new Error() }
        this.rewardCount = _json_.reward_count
        if (_json_.next_id === undefined) { throw new Error() }
        this.nextId = _json_.next_id
        if (_json_.sort === undefined) { throw new Error() }
        this.sort = _json_.sort
    }

    readonly id: number
    readonly name: string
    readonly desc: string
    readonly conditionId: number
    readonly param: string
    readonly num: number
    readonly gotoId: number
    readonly rewardGold: number
    readonly rewardItem: string
    readonly rewardCount: number
    readonly nextId: number
    readonly sort: number

    resolve(tables:Tables) {
        
        
        
        
        
        
        
        
        
        
        
        
    }
}






/**
 * 条件模板
 */
export class TCondition {
    private _dataMap: Map<number, CCondition>
    private _dataList: CCondition[]
    constructor(_json_: any) {
        this._dataMap = new Map<number, CCondition>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: CCondition
            _v = new CCondition(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.id, _v)
        }
    }

    getDataMap(): Map<number, CCondition> { return this._dataMap; }
    getDataList(): CCondition[] { return this._dataList; }

    get(key: number): CCondition | undefined { return this._dataMap.get(key); }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




/**
 * 合成配方
 */
export class TCraftRecipe {
    private _dataMap: Map<string, CCraftRecipe>
    private _dataList: CCraftRecipe[]
    constructor(_json_: any) {
        this._dataMap = new Map<string, CCraftRecipe>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: CCraftRecipe
            _v = new CCraftRecipe(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.id, _v)
        }
    }

    getDataMap(): Map<string, CCraftRecipe> { return this._dataMap; }
    getDataList(): CCraftRecipe[] { return this._dataList; }

    get(key: string): CCraftRecipe | undefined { return this._dataMap.get(key); }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




/**
 * 合成消耗
 */
export class TCraftCost {
    private _dataMap: Map<number, CCraftCost>
    private _dataList: CCraftCost[]
    constructor(_json_: any) {
        this._dataMap = new Map<number, CCraftCost>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: CCraftCost
            _v = new CCraftCost(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.id, _v)
        }
    }

    getDataMap(): Map<number, CCraftCost> { return this._dataMap; }
    getDataList(): CCraftCost[] { return this._dataList; }

    get(key: number): CCraftCost | undefined { return this._dataMap.get(key); }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




/**
 * 主线任务
 */
export class TQuest {
    private _dataMap: Map<number, CQuest>
    private _dataList: CQuest[]
    constructor(_json_: any) {
        this._dataMap = new Map<number, CQuest>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: CQuest
            _v = new CQuest(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.id, _v)
        }
    }

    getDataMap(): Map<number, CQuest> { return this._dataMap; }
    getDataList(): CQuest[] { return this._dataList; }

    get(key: number): CQuest | undefined { return this._dataMap.get(key); }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




/**
 * 引导跳转
 */
export class TGoto {
    private _dataMap: Map<number, CGoto>
    private _dataList: CGoto[]
    constructor(_json_: any) {
        this._dataMap = new Map<number, CGoto>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: CGoto
            _v = new CGoto(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.id, _v)
        }
    }

    getDataMap(): Map<number, CGoto> { return this._dataMap; }
    getDataList(): CGoto[] { return this._dataList; }

    get(key: number): CGoto | undefined { return this._dataMap.get(key); }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




type JsonLoader = (file: string) => any

export class Tables {
    private _TCondition: TCondition
    /**
     * 条件模板
     */
    get TCondition(): TCondition  { return this._TCondition;}
    private _TCraftRecipe: TCraftRecipe
    /**
     * 合成配方
     */
    get TCraftRecipe(): TCraftRecipe  { return this._TCraftRecipe;}
    private _TCraftCost: TCraftCost
    /**
     * 合成消耗
     */
    get TCraftCost(): TCraftCost  { return this._TCraftCost;}
    private _TQuest: TQuest
    /**
     * 主线任务
     */
    get TQuest(): TQuest  { return this._TQuest;}
    private _TGoto: TGoto
    /**
     * 引导跳转
     */
    get TGoto(): TGoto  { return this._TGoto;}

    constructor(loader: JsonLoader) {
        this._TCondition = new TCondition(loader('tcondition'))
        this._TCraftRecipe = new TCraftRecipe(loader('tcraftrecipe'))
        this._TCraftCost = new TCraftCost(loader('tcraftcost'))
        this._TQuest = new TQuest(loader('tquest'))
        this._TGoto = new TGoto(loader('tgoto'))

        this._TCondition.resolve(this)
        this._TCraftRecipe.resolve(this)
        this._TCraftCost.resolve(this)
        this._TQuest.resolve(this)
        this._TGoto.resolve(this)
    }
}

