import * as fs from 'fs';
import { listLocalGuides } from '../browseGuides';
import { writeFsText } from '../assetIo';
import { CLASS_PREFIX, classMapFsPath, ensureDir, generatedClassFsPath, generatedDirFs } from '../paths';

export function regenerateClassMap(): { ok: boolean; count: number; path: string } {
  ensureDir(generatedDirFs());
  const items = listLocalGuides().filter(
    (s) => s.exportFlag && fs.existsSync(generatedClassFsPath(s.guideId))
  );

  const imports: string[] = [];
  const entries: string[] = [];

  for (const s of items) {
    const cls = `${CLASS_PREFIX}${s.guideId}`;
    imports.push(`import { ${cls} } from './${cls}';`);
    entries.push(`  ${s.guideId}: () => new ${cls}(),`);
  }

  const code = `/*
 * AUTO-GENERATED by guide-editor. Do not edit manually.
 */
import type { AbsGuide } from '../AbsGuide';
${imports.join('\n')}

const MAP: Record<number, () => AbsGuide> = {
${entries.join('\n')}
};

export function createTsGuide(guideId: number): AbsGuide | null {
  const factory = MAP[guideId | 0];
  return factory ? factory() : null;
}

export function listExportedGuideIds(): number[] {
  return Object.keys(MAP).map((k) => Number(k));
}
`;

  const out = classMapFsPath();
  writeFsText(out, code);
  return { ok: true, count: items.length, path: out };
}
