/*
 * AUTO-GENERATED by guide-editor from guide graph {{GUIDE_ID}}.
 * Do not edit manually — re-export from the guide editor.
 */
import { AbsGuide } from '../AbsGuide';

export class {{CLASS_NAME}} extends AbsGuide {
    public readonly guideId = {{GUIDE_ID}};
{{FIELDS}}
{{LIFECYCLE_METHODS}}
{{BLUEPRINT_METHODS}}
}
