#!/usr/bin/env python3
"""Generate TutorialGuide.prefab + TutorialGuideFrames.ts — tip chrome shell.

  /opt/homebrew/bin/python3.12 tools/ui/generate_tutorial_guide_prefab.py

Motion (Dim/Ring/Finger/Tip aim) stays in TutorialGuide.ts; sizes/structure from prefab.
"""
from __future__ import annotations

import json
import uuid
from pathlib import Path

from cocos_prefab_lib import PrefabBuilder

ROOT = Path(__file__).resolve().parents[2]
OUT_PREFAB = ROOT / "assets/prefabs/ui/TutorialGuide.prefab"
OUT_TS = ROOT / "assets/scripts/game/TutorialGuideFrames.ts"

TIP_W, TIP_H = 560, 64
FINGER = 96
DRAG_GHOST = 72
CLICK_LAB_W, CLICK_LAB_H = 80, 48
ARROW_EXTENT_UP = 48
CLICK_LAB_GAP = 20
CLICK_LAB_Y = ARROW_EXTENT_UP + CLICK_LAB_H * 0.5 + CLICK_LAB_GAP
TIP_LAB = (255, 244, 214, 255)
CLICK_LAB = (255, 248, 220, 255)
# QUEST_FRAMES.questArrow — bake so idle chevron never waits on async load.
QUEST_ARROW_SF = "74358256-5fdf-4193-a127-53998d13c454@f9941"


def build() -> PrefabBuilder:
    b = PrefabBuilder("TutorialGuide")
    root = b.node("TutorialGuideRoot", None, 0, 0, 10, 10, active=False)
    assert root == 1

    dim = b.node("Dim", root, 0, 0, 10, 10, with_graphics=True)
    ring = b.node("Ring", root, 0, 0, 10, 10, with_graphics=True)
    trail = b.node("DragTrail", root, 0, 0, 10, 10, with_graphics=True, active=False)
    # Sprite assigned at runtime (quest arrow / item icon).
    ghost = b.node("DragGhost", root, 0, 0, DRAG_GHOST, DRAG_GHOST, active=False)

    # Sprite on Finger; Graphics fallback is a CHILD — same-node Graphics+Sprite
    # after instantiate used to clear the chevron while「点击」label still showed.
    finger = b.node("Finger", root, 0, 0, FINGER, FINGER, sprite=QUEST_ARROW_SF)
    fallback = b.node("Fallback", finger, 0, 0, FINGER, FINGER, with_graphics=True, active=False)
    click = b.node(
        "ClickLab",
        finger,
        0,
        CLICK_LAB_Y,
        CLICK_LAB_W,
        CLICK_LAB_H,
        active=False,
        label={
            "text": "点击",
            "size": 34,
            "color": CLICK_LAB,
            "h_align": 1,
            "outline": True,
            "overflow": 2,
        },
    )
    b.set_children(finger, [fallback, click])

    tip = b.node("Tip", root, 0, 0, TIP_W, TIP_H, with_graphics=True)
    tip_lab = b.node(
        "TipLab",
        tip,
        0,
        0,
        TIP_W - 40,
        TIP_H - 16,
        label={
            "text": "",
            "size": 30,
            "color": TIP_LAB,
            "h_align": 1,
            "outline": True,
            "overflow": 2,
        },
    )
    b.set_children(tip, [tip_lab])

    b.set_children(root, [dim, ring, trail, ghost, finger, tip])
    return b


def write_meta(path: Path, name: str, prefab_uuid: str) -> str:
    meta_path = Path(str(path) + ".meta")
    if meta_path.exists():
        prefab_uuid = json.loads(meta_path.read_text(encoding="utf-8")).get("uuid", prefab_uuid)
    meta = {
        "ver": "1.1.50",
        "importer": "prefab",
        "imported": True,
        "uuid": prefab_uuid,
        "files": [".json"],
        "subMetas": {},
        "userData": {"syncNodeName": name},
    }
    meta_path.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
    return prefab_uuid


def main() -> None:
    prefab_uuid = str(uuid.uuid4())
    meta_path = Path(str(OUT_PREFAB) + ".meta")
    if meta_path.exists():
        prefab_uuid = json.loads(meta_path.read_text(encoding="utf-8")).get("uuid", prefab_uuid)

    pb = build()
    OUT_PREFAB.parent.mkdir(parents=True, exist_ok=True)
    OUT_PREFAB.write_text(json.dumps(pb.items, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    prefab_uuid = write_meta(OUT_PREFAB, "TutorialGuideRoot", prefab_uuid)

    values = {
        "tipW": TIP_W,
        "tipH": TIP_H,
        "finger": FINGER,
        "dragGhost": DRAG_GHOST,
        "clickLabW": CLICK_LAB_W,
        "clickLabH": CLICK_LAB_H,
        "clickLabY": CLICK_LAB_Y,
    }
    lines = [
        "/** Auto-generated by tools/ui/generate_tutorial_guide_prefab.py — do not edit by hand. */",
        f"export const TUTORIAL_GUIDE_PREFAB_UUID = '{prefab_uuid}';",
        "",
        "/** Prefab layout (canvas-local px). */",
        "export const TUTORIAL_GUIDE_LAYOUT = {",
    ]
    for k, v in values.items():
        if isinstance(v, float):
            lines.append(f"    {k}: {round(v, 1)},")
        else:
            lines.append(f"    {k}: {v},")
    lines.append("} as const;")
    lines.append("")
    OUT_TS.write_text("\n".join(lines), encoding="utf-8")
    print("wrote", OUT_PREFAB, prefab_uuid)
    print("patched", OUT_TS)


if __name__ == "__main__":
    main()
