#!/usr/bin/env python3
"""Generate StickVisual.prefab + StickVisualFrames.ts — rest-dock stick chrome.

  /opt/homebrew/bin/python3.12 tools/ui/generate_stick_visual_prefab.py
"""
from __future__ import annotations

import json
import re
import uuid
from pathlib import Path

from cocos_prefab_lib import PrefabBuilder

ROOT = Path(__file__).resolve().parents[2]
OUT_PREFAB = ROOT / "assets/prefabs/ui/StickVisual.prefab"
OUT_TS = ROOT / "assets/scripts/game/StickVisualFrames.ts"
JOYSTICK_FRAMES_TS = ROOT / "assets/scripts/game/JoystickFrames.ts"

VISUAL = 180
BASE = 160
KNOB = 80
# Rest dock — mirrored in TouchJoystick REST_STICK_* / StickVisualFrames.
REST_X, REST_Y = 0, -600


def load_joy_sf(key: str) -> str:
    text = JOYSTICK_FRAMES_TS.read_text(encoding="utf-8")
    m = re.search(rf'"{key}"\s*:\s*"([^"]+)"', text)
    if not m:
        raise SystemExit(f"missing JOYSTICK_FRAMES.{key}")
    return m.group(1)


def build(base_sf: str, knob_sf: str) -> PrefabBuilder:
    b = PrefabBuilder("StickVisual")
    root = b.node("StickVisual", None, REST_X, REST_Y, VISUAL, VISUAL)
    assert root == 1
    base = b.node("Base", root, 0, 0, BASE, BASE, sprite=base_sf, with_graphics=True)
    knob = b.node("Knob", root, 0, 0, KNOB, KNOB, sprite=knob_sf, with_graphics=True)
    b.set_children(root, [base, knob])
    return b


def write_meta(path: Path, name: str, prefab_uuid: str) -> str:
    meta_path = Path(str(path) + ".meta")
    if meta_path.exists():
        prefab_uuid = json.loads(meta_path.read_text(encoding="utf-8")).get("uuid", prefab_uuid)
    meta = {
        "ver": "1.1.50",
        "importer": "prefab",
        "imported": True,
        "uuid": prefab_uuid,
        "files": [".json"],
        "subMetas": {},
        "userData": {"syncNodeName": name},
    }
    meta_path.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
    return prefab_uuid


def main() -> None:
    base_sf = load_joy_sf("base")
    knob_sf = load_joy_sf("knob")

    prefab_uuid = str(uuid.uuid4())
    meta_path = Path(str(OUT_PREFAB) + ".meta")
    if meta_path.exists():
        prefab_uuid = json.loads(meta_path.read_text(encoding="utf-8")).get("uuid", prefab_uuid)

    pb = build(base_sf, knob_sf)
    OUT_PREFAB.parent.mkdir(parents=True, exist_ok=True)
    OUT_PREFAB.write_text(json.dumps(pb.items, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    prefab_uuid = write_meta(OUT_PREFAB, "StickVisual", prefab_uuid)

    values = {
        "visual": VISUAL,
        "base": BASE,
        "knob": KNOB,
        "restX": REST_X,
        "restY": REST_Y,
        "radius": 80,
    }
    lines = [
        "/** Auto-generated by tools/ui/generate_stick_visual_prefab.py — do not edit by hand. */",
        f"export const STICK_VISUAL_PREFAB_UUID = '{prefab_uuid}';",
        "",
        "/** Prefab layout (canvas-local px). */",
        "export const STICK_VISUAL_LAYOUT = {",
    ]
    for k, v in values.items():
        if isinstance(v, float):
            lines.append(f"    {k}: {round(v, 1)},")
        else:
            lines.append(f"    {k}: {v},")
    lines.append("} as const;")
    lines.append("")
    OUT_TS.write_text("\n".join(lines), encoding="utf-8")
    print("wrote", OUT_PREFAB, prefab_uuid)
    print("patched", OUT_TS)


if __name__ == "__main__":
    main()
