#!/usr/bin/env python3
"""Generate QuestPanel.prefab — layout source of truth (wood/parchment journal).

  /opt/homebrew/bin/python3.12 tools/ui/generate_quest_panel_prefab.py

Layout (panel-local, center origin). Mirrored in QuestFrames.ts QUEST_LAYOUT.
"""
from __future__ import annotations

import json
import uuid
from pathlib import Path

from cocos_prefab_lib import CLOSE_SF, PrefabBuilder

ROOT = Path(__file__).resolve().parents[2]
OUT_PREFAB = ROOT / "assets/prefabs/ui/QuestPanel.prefab"
QUEST_FRAMES_JSON = Path(__file__).resolve().parent / "quest-frames.json"
OUT_TS = ROOT / "assets/scripts/game/QuestFrames.ts"

# --- Layout (panel-local) — must match QuestPanel runtime chrome ---
PANEL_W, PANEL_H = 700, 1120
PANEL_Y = 10
CONTENT_W = PANEL_W - 80
CLOSE_BTN, CLOSE_PAD = 84, 33
CLOSE_HIT = int(CLOSE_BTN * 1.85)
CLOSE_X = PANEL_W * 0.5 - CLOSE_PAD - CLOSE_BTN * 0.5
CLOSE_Y = PANEL_H * 0.5 - CLOSE_PAD - CLOSE_BTN * 0.5

TITLE_Y = PANEL_H * 0.5 - 78
TITLE_W = int(PANEL_W - CLOSE_BTN * 2.8)

TAB_W, TAB_H, TAB_GAP = 168, 48, 20
TAB_Y = TITLE_Y - 70
TAB_LEFT_X = -(TAB_W + TAB_GAP) * 0.5
TAB_RIGHT_X = (TAB_W + TAB_GAP) * 0.5

LIST_TOP = TAB_Y - TAB_H * 0.5 - 22
LIST_BOTTOM = -PANEL_H * 0.5 + 40
LIST_H = max(200, int(LIST_TOP - LIST_BOTTOM))
LIST_Y = (LIST_TOP + LIST_BOTTOM) * 0.5

SCROLL_W = 12
SCROLL_X = CONTENT_W * 0.5 - SCROLL_W * 0.5 - 2

# Dynamic rows still code-built; these are layout hints / legacy sync.
ROW_W, ROW_H, ROW_GAP = CONTENT_W, 210, 16
ICON = 44

INK = (62, 40, 22, 255)
TITLE_CREAM = (255, 244, 214, 255)


def build_panel() -> PrefabBuilder:
    b = PrefabBuilder("QuestPanel")
    root = b.node("QuestPanel", None, 0, 0, 1080, 1920, active=False)
    assert root == 1

    dim = b.node("Dim", root, 0, 0, 2200, 4000, with_graphics=True)
    panel = b.node("Panel", root, 0, PANEL_Y, PANEL_W, PANEL_H)
    chrome = b.node("Chrome", panel, 0, 0, PANEL_W, PANEL_H, with_graphics=True)

    title = b.node(
        "Title",
        panel,
        0,
        TITLE_Y,
        TITLE_W,
        48,
        label={
            "text": "旅途日志",
            "size": 36,
            "color": TITLE_CREAM,
            "h_align": 1,
            "outline": True,
            "bold": True,
            "overflow": 2,
        },
    )

    main_tab = b.node(
        "TabMain", panel, TAB_LEFT_X, TAB_Y, TAB_W, TAB_H, with_graphics=True
    )
    main_lab = b.node(
        "Lab",
        main_tab,
        0,
        0,
        TAB_W,
        TAB_H,
        label={"text": "主线", "size": 30, "color": INK, "h_align": 1},
    )
    b.set_children(main_tab, [main_lab])

    board_tab = b.node(
        "TabBoard", panel, TAB_RIGHT_X, TAB_Y, TAB_W, TAB_H, with_graphics=True
    )
    board_lab = b.node(
        "Lab",
        board_tab,
        0,
        0,
        TAB_W,
        TAB_H,
        label={"text": "委托", "size": 30, "color": INK, "h_align": 1},
    )
    b.set_children(board_tab, [board_lab])

    list_host = b.node("List", panel, 0, LIST_Y, CONTENT_W, LIST_H)

    scroll = b.node(
        "ScrollBar", panel, SCROLL_X, LIST_Y, SCROLL_W, LIST_H, with_graphics=True
    )
    thumb = b.node(
        "Thumb", scroll, 0, 0, SCROLL_W - 2, 48, with_graphics=True
    )
    b.set_children(scroll, [thumb])

    close = b.node("BtnClose", panel, CLOSE_X, CLOSE_Y, CLOSE_HIT, CLOSE_HIT)
    close_icon = b.node("Icon", close, 0, 0, CLOSE_BTN, CLOSE_BTN, sprite=CLOSE_SF)
    b.set_children(close, [close_icon])

    b.set_children(
        panel,
        [chrome, title, main_tab, board_tab, list_host, scroll, close],
    )
    b.set_children(root, [dim, panel])
    return b


def write_meta(prefab_uuid: str) -> str:
    meta_path = Path(str(OUT_PREFAB) + ".meta")
    if meta_path.exists():
        prefab_uuid = json.loads(meta_path.read_text(encoding="utf-8")).get(
            "uuid", prefab_uuid
        )
    meta = {
        "ver": "1.1.50",
        "importer": "prefab",
        "imported": True,
        "uuid": prefab_uuid,
        "files": [".json"],
        "subMetas": {},
        "userData": {"syncNodeName": "QuestPanel"},
    }
    meta_path.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
    return prefab_uuid


def patch_frames_ts(prefab_uuid: str) -> None:
    frames = json.loads(QUEST_FRAMES_JSON.read_text(encoding="utf-8"))
    lines = [
        "/** Auto-generated by tools/ui/generate_quest_panel_prefab.py — do not edit by hand. */",
        "export const QUEST_FRAMES = {",
    ]
    for k, v in frames.items():
        sf = v["spriteFrame"] if isinstance(v, dict) else v
        lines.append(f"    {k}: '{sf}',")
    lines.append("} as const;")
    lines.append("")
    lines.append("/** Prefab asset uuid — layout source of truth. */")
    lines.append(f"export const QUEST_PANEL_PREFAB_UUID = '{prefab_uuid}';")
    lines.append("")
    lines.append("/** Prefab layout (panel-local px). */")
    lines.append("export const QUEST_LAYOUT = {")
    values = {
        "panelW": PANEL_W,
        "panelH": PANEL_H,
        "panelY": PANEL_Y,
        "contentW": CONTENT_W,
        "rowW": ROW_W,
        "rowH": ROW_H,
        "rowGap": ROW_GAP,
        "listTop": LIST_TOP,
        "listY": LIST_Y,
        "listH": LIST_H,
        "titleY": TITLE_Y,
        "tabY": TAB_Y,
        "tabW": TAB_W,
        "tabH": TAB_H,
        "tabGap": TAB_GAP,
        "tabLeftX": TAB_LEFT_X,
        "tabRightX": TAB_RIGHT_X,
        "scrollW": SCROLL_W,
        "scrollX": SCROLL_X,
        "closeX": CLOSE_X,
        "closeY": CLOSE_Y,
        "closeBtn": CLOSE_BTN,
        "closePad": CLOSE_PAD,
        "closeHit": CLOSE_HIT,
        "icon": ICON,
    }
    for name, val in values.items():
        if isinstance(val, float):
            lines.append(f"    {name}: {round(val, 1)},")
        else:
            lines.append(f"    {name}: {val},")
    lines.append("} as const;")
    lines.append("")
    OUT_TS.write_text("\n".join(lines), encoding="utf-8")
    print("patched", OUT_TS)


def main() -> None:
    meta_path = Path(str(OUT_PREFAB) + ".meta")
    prefab_uuid = str(uuid.uuid4())
    if meta_path.exists():
        prefab_uuid = json.loads(meta_path.read_text(encoding="utf-8")).get(
            "uuid", prefab_uuid
        )

    pb = build_panel()
    OUT_PREFAB.parent.mkdir(parents=True, exist_ok=True)
    OUT_PREFAB.write_text(
        json.dumps(pb.items, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    prefab_uuid = write_meta(prefab_uuid)
    patch_frames_ts(prefab_uuid)
    print("wrote", OUT_PREFAB, prefab_uuid)


if __name__ == "__main__":
    main()
