#!/usr/bin/env python3
"""Generate StoryIntroPanel.prefab + StoryIntroPanelFrames.ts — layout source of truth.

  /opt/homebrew/bin/python3.12 tools/ui/generate_story_intro_panel_prefab.py
"""
from __future__ import annotations

import json
import uuid
from pathlib import Path

from cocos_prefab_lib import PrefabBuilder

ROOT = Path(__file__).resolve().parents[2]
OUT_PREFAB = ROOT / "assets/prefabs/ui/StoryIntroPanel.prefab"
OUT_TS = ROOT / "assets/scripts/game/StoryIntroPanelFrames.ts"

# Match DialoguePanel caption chrome + design-space skip (1080×1920).
DESIGN_W, DESIGN_H = 1080, 1920
BOX_W, BOX_H = 1000, 260
BOX_Y = -780
BODY_Y = 96
BODY_W = BOX_W - 100
HINT_X = -BOX_W * 0.5 + BOX_W - 118
HINT_Y = -BOX_H * 0.5 + 70
ARROW_Y = 16
ART_W, ART_H = 720, 1080
ART_Y = 180
SKIP_W, SKIP_H = 148, 56
SKIP_PAD = 36
SKIP_X = DESIGN_W * 0.5 - SKIP_PAD - SKIP_W * 0.5
SKIP_Y = DESIGN_H * 0.5 - SKIP_PAD - SKIP_H * 0.5
CREAM = (255, 246, 220, 255)
HINT_GOLD = (255, 230, 150, 255)


def build() -> PrefabBuilder:
    b = PrefabBuilder("StoryIntroPanel")
    root = b.node("StoryIntro", None, 0, 0, DESIGN_W, DESIGN_H, active=False)
    assert root == 1

    veil = b.node("Veil", root, 0, 0, 2400, 3200, with_graphics=True)
    art = b.node("Art", root, 0, ART_Y, ART_W, ART_H, sprite="")
    for item in b.items:
        if isinstance(item, dict) and item.get("__type__") == "cc.Sprite" and item.get("node", {}).get("__id__") == art:
            item["_spriteFrame"] = None

    caption = b.node("Caption", root, 0, BOX_Y, BOX_W, BOX_H, with_graphics=True)
    body = b.node(
        "Body",
        caption,
        0,
        BODY_Y,
        BODY_W,
        150,
        label={
            "text": "",
            "size": 34,
            "color": CREAM,
            "h_align": 0,
            "outline": True,
            "overflow": 3,
            "wrap": True,
        },
    )
    for item in b.items:
        if isinstance(item, dict) and item.get("__type__") == "cc.UITransform" and item.get("node", {}).get("__id__") == body:
            item["_anchorPoint"] = {"__type__": "cc.Vec2", "x": 0.5, "y": 1}

    hint = b.node("Hint", caption, HINT_X, HINT_Y, 200, 64, active=False)
    arrow = b.node("HintArrow", hint, 0, ARROW_Y, 36, 24, with_graphics=True)
    hint_lab = b.node(
        "HintLab",
        hint,
        0,
        -14,
        200,
        32,
        label={
            "text": "点击继续",
            "size": 24,
            "color": HINT_GOLD,
            "h_align": 1,
            "outline": True,
            "overflow": 1,
        },
    )
    b.set_children(hint, [arrow, hint_lab])
    b.set_children(caption, [body, hint])

    skip = b.node("SkipBtn", root, SKIP_X, SKIP_Y, SKIP_W, SKIP_H, with_graphics=True)
    skip_lab = b.node(
        "Label",
        skip,
        0,
        0,
        SKIP_W,
        SKIP_H,
        label={
            "text": "跳过",
            "size": 28,
            "color": CREAM,
            "h_align": 1,
            "outline": True,
        },
    )
    b.set_children(skip, [skip_lab])

    b.set_children(root, [veil, art, caption, skip])
    return b


def write_meta(path: Path, name: str, prefab_uuid: str) -> str:
    meta_path = Path(str(path) + ".meta")
    if meta_path.exists():
        prefab_uuid = json.loads(meta_path.read_text(encoding="utf-8")).get("uuid", prefab_uuid)
    meta = {
        "ver": "1.1.50",
        "importer": "prefab",
        "imported": True,
        "uuid": prefab_uuid,
        "files": [".json"],
        "subMetas": {},
        "userData": {"syncNodeName": name},
    }
    meta_path.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
    return prefab_uuid


def main():
    prefab_uuid = str(uuid.uuid4())
    meta_path = Path(str(OUT_PREFAB) + ".meta")
    if meta_path.exists():
        prefab_uuid = json.loads(meta_path.read_text(encoding="utf-8")).get("uuid", prefab_uuid)

    pb = build()
    OUT_PREFAB.parent.mkdir(parents=True, exist_ok=True)
    OUT_PREFAB.write_text(json.dumps(pb.items, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    # syncNodeName must match root node (StoryIntro) so Cocos import doesn't rename.
    prefab_uuid = write_meta(OUT_PREFAB, "StoryIntro", prefab_uuid)

    values = {
        "designW": DESIGN_W,
        "designH": DESIGN_H,
        "boxW": BOX_W,
        "boxH": BOX_H,
        "boxY": BOX_Y,
        "bodyY": BODY_Y,
        "bodyW": BODY_W,
        "hintX": HINT_X,
        "hintY": HINT_Y,
        "arrowY": ARROW_Y,
        "artW": ART_W,
        "artH": ART_H,
        "artY": ART_Y,
        "skipW": SKIP_W,
        "skipH": SKIP_H,
        "skipPad": SKIP_PAD,
        "skipX": SKIP_X,
        "skipY": SKIP_Y,
    }
    lines = [
        "/** Auto-generated by tools/ui/generate_story_intro_panel_prefab.py — do not edit by hand. */",
        f"export const STORY_INTRO_PANEL_PREFAB_UUID = '{prefab_uuid}';",
        "",
        "/** Prefab layout (design-space px). */",
        "export const STORY_INTRO_PANEL_LAYOUT = {",
    ]
    for k, v in values.items():
        if isinstance(v, float):
            lines.append(f"    {k}: {round(v, 1)},")
        else:
            lines.append(f"    {k}: {v},")
    lines.append("} as const;")
    lines.append("")
    OUT_TS.write_text("\n".join(lines), encoding="utf-8")
    print("wrote", OUT_PREFAB, prefab_uuid)
    print("patched", OUT_TS)


if __name__ == "__main__":
    main()
