#!/usr/bin/env python3
"""Generate QuestTracker.prefab + QuestTrackerFrames.ts — claim dock above hotbar.

  /opt/homebrew/bin/python3.12 tools/ui/generate_quest_tracker_prefab.py
"""
from __future__ import annotations

import json
import uuid
from pathlib import Path

from cocos_prefab_lib import PrefabBuilder

ROOT = Path(__file__).resolve().parents[2]
OUT_PREFAB = ROOT / "assets/prefabs/ui/QuestTracker.prefab"
OUT_TS = ROOT / "assets/scripts/game/QuestTrackerFrames.ts"

# Must match QuestPanel HUD_* constants.
HUD_BAR_Y = -860
HUD_BAR_H = 150 + 30
HUD_BAR_W = 7 * 150 + 6 * 4 + 6
HUD_CLEARANCE = 28
EDGE_PAD = 16
TW, TH = 420, 120
HOTBAR_TOP = HUD_BAR_Y + HUD_BAR_H * 0.5
DOCK_Y = HOTBAR_TOP + HUD_CLEARANCE + TH * 0.5
BAR_X = -HUD_BAR_W * 0.5 + TW * 0.5 + EDGE_PAD

TEXT_LEFT = -TW * 0.5 + 24
TEXT_RIGHT = TW * 0.5 - 24
OBJ_W = TW - 48 - 110
COUNT_W = 100
TITLE_Y = 18
ROW_Y = -22
INK = (62, 40, 22, 255)
INK_MUTE = (110, 88, 64, 255)


def build() -> PrefabBuilder:
    b = PrefabBuilder("QuestTracker")
    # Root is QuestHud dock (identity); tracker bar is the painted chrome.
    root = b.node("QuestHud", None, 0, 0, 1, 1, active=False)
    assert root == 1

    bar = b.node("QuestTracker", root, BAR_X, DOCK_Y, TW, TH, with_graphics=True)

    title = b.node(
        "Title",
        bar,
        TEXT_LEFT,
        TITLE_Y,
        TW - 48,
        40,
        label={"text": "", "size": 30, "color": INK, "h_align": 0},
    )
    prog = b.node(
        "Prog",
        bar,
        TEXT_LEFT,
        ROW_Y,
        OBJ_W,
        40,
        label={"text": "", "size": 30, "color": INK_MUTE, "h_align": 0},
    )
    count = b.node(
        "Count",
        bar,
        TEXT_RIGHT,
        ROW_Y,
        COUNT_W,
        40,
        label={"text": "", "size": 30, "color": INK, "h_align": 2},
    )
    # Left / right anchors for title/prog/count.
    for nid, ax in ((title, 0.0), (prog, 0.0), (count, 1.0)):
        for item in b.items:
            if (
                isinstance(item, dict)
                and item.get("__type__") == "cc.UITransform"
                and item.get("node", {}).get("__id__") == nid
            ):
                item["_anchorPoint"] = {"__type__": "cc.Vec2", "x": ax, "y": 0.5}

    b.set_children(bar, [title, prog, count])
    b.set_children(root, [bar])
    return b


def write_meta(path: Path, name: str, prefab_uuid: str) -> str:
    meta_path = Path(str(path) + ".meta")
    if meta_path.exists():
        prefab_uuid = json.loads(meta_path.read_text(encoding="utf-8")).get("uuid", prefab_uuid)
    meta = {
        "ver": "1.1.50",
        "importer": "prefab",
        "imported": True,
        "uuid": prefab_uuid,
        "files": [".json"],
        "subMetas": {},
        "userData": {"syncNodeName": name},
    }
    meta_path.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
    return prefab_uuid


def main() -> None:
    prefab_uuid = str(uuid.uuid4())
    meta_path = Path(str(OUT_PREFAB) + ".meta")
    if meta_path.exists():
        prefab_uuid = json.loads(meta_path.read_text(encoding="utf-8")).get("uuid", prefab_uuid)

    pb = build()
    OUT_PREFAB.parent.mkdir(parents=True, exist_ok=True)
    OUT_PREFAB.write_text(json.dumps(pb.items, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    prefab_uuid = write_meta(OUT_PREFAB, "QuestHud", prefab_uuid)

    values = {
        "barW": TW,
        "barH": TH,
        "barX": BAR_X,
        "dockY": DOCK_Y,
        "edgePad": EDGE_PAD,
        "titleY": TITLE_Y,
        "rowY": ROW_Y,
        "textLeft": TEXT_LEFT,
        "textRight": TEXT_RIGHT,
        "objW": OBJ_W,
        "countW": COUNT_W,
    }
    lines = [
        "/** Auto-generated by tools/ui/generate_quest_tracker_prefab.py — do not edit by hand. */",
        f"export const QUEST_TRACKER_PREFAB_UUID = '{prefab_uuid}';",
        "",
        "/** Prefab layout (canvas-local px). */",
        "export const QUEST_TRACKER_LAYOUT = {",
    ]
    for k, v in values.items():
        if isinstance(v, float):
            lines.append(f"    {k}: {round(v, 1)},")
        else:
            lines.append(f"    {k}: {v},")
    lines.append("} as const;")
    lines.append("")
    OUT_TS.write_text("\n".join(lines), encoding="utf-8")
    print("wrote", OUT_PREFAB, prefab_uuid)
    print("patched", OUT_TS)


if __name__ == "__main__":
    main()
