#!/usr/bin/env python3
"""Generate LoadingScreen.prefab + LoadingScreenFrames.ts — layout source of truth.

  /opt/homebrew/bin/python3.12 tools/ui/generate_loading_screen_prefab.py
"""
from __future__ import annotations

import json
import uuid
from pathlib import Path

from cocos_prefab_lib import PrefabBuilder

ROOT = Path(__file__).resolve().parents[2]
OUT_PREFAB = ROOT / "assets/prefabs/ui/LoadingScreen.prefab"
OUT_TS = ROOT / "assets/scripts/game/LoadingScreenFrames.ts"

DESIGN_W = 1080
SPLASH_W, SPLASH_H = 1080, 2200
SPLASH_SF = "5a4ebb12-2f98-4075-a870-b9286e9ac348@f9941"
DOCK_Y_LOADING = -880
DOCK_Y_READY = -640
TITLE_Y, SUB_Y = 820, 740
BAR_W, BAR_H = 720, 32
TRACK_W, TRACK_H = BAR_W + 14, BAR_H + 14
BAR_TRACK_Y = 24
TIP_Y = -30
GOLD = (255, 236, 180, 255)
SUB = (230, 220, 180, 240)
TIP = (255, 242, 210, 255)


def build() -> PrefabBuilder:
    b = PrefabBuilder("LoadingScreen")
    root = b.node("LoadingScreen", None, 0, 0, DESIGN_W, SPLASH_H, active=True)
    assert root == 1

    veil = b.node("Veil", root, 0, 0, 2400, 3200, with_graphics=True)
    splash = b.node("Splash", root, 0, 0, SPLASH_W, SPLASH_H, sprite=SPLASH_SF)

    title = b.node(
        "Title",
        root,
        0,
        TITLE_Y,
        900,
        100,
        label={
            "text": "微光溪谷",
            "size": 72,
            "color": GOLD,
            "h_align": 1,
            "outline": True,
        },
    )
    sub = b.node(
        "Sub",
        root,
        0,
        SUB_Y,
        700,
        40,
        label={
            "text": "Lumewisp Vale",
            "size": 28,
            "color": SUB,
            "h_align": 1,
            "outline": True,
        },
    )

    dock = b.node("ProgressDock", root, 0, DOCK_Y_LOADING, 900, 160)
    track = b.node("BarTrack", dock, 0, BAR_TRACK_Y, TRACK_W, TRACK_H, with_graphics=True)
    fill = b.node("BarFill", track, 0, 0, BAR_W, BAR_H, with_graphics=True)
    b.set_children(track, [fill])

    tip = b.node(
        "Tip",
        dock,
        0,
        TIP_Y,
        900,
        40,
        label={
            "text": "正在唤醒溪谷…",
            "size": 28,
            "color": TIP,
            "h_align": 1,
            "outline": True,
        },
    )

    start = b.node("StartHint", dock, 0, 0, 900, 72, active=False)
    start_lab = b.node(
        "Label",
        start,
        0,
        0,
        900,
        72,
        label={
            "text": "点击开始游戏",
            "size": 48,
            "color": TIP,
            "h_align": 1,
            "outline": True,
        },
    )
    b.set_children(start, [start_lab])
    b.set_children(dock, [track, tip, start])
    b.set_children(root, [veil, splash, title, sub, dock])
    return b


def write_meta(path: Path, name: str, prefab_uuid: str) -> str:
    meta_path = Path(str(path) + ".meta")
    if meta_path.exists():
        prefab_uuid = json.loads(meta_path.read_text(encoding="utf-8")).get("uuid", prefab_uuid)
    meta = {
        "ver": "1.1.50",
        "importer": "prefab",
        "imported": True,
        "uuid": prefab_uuid,
        "files": [".json"],
        "subMetas": {},
        "userData": {"syncNodeName": name},
    }
    meta_path.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
    return prefab_uuid


def main():
    prefab_uuid = str(uuid.uuid4())
    meta_path = Path(str(OUT_PREFAB) + ".meta")
    if meta_path.exists():
        prefab_uuid = json.loads(meta_path.read_text(encoding="utf-8")).get("uuid", prefab_uuid)

    pb = build()
    OUT_PREFAB.parent.mkdir(parents=True, exist_ok=True)
    OUT_PREFAB.write_text(json.dumps(pb.items, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    prefab_uuid = write_meta(OUT_PREFAB, "LoadingScreen", prefab_uuid)

    values = {
        "designW": DESIGN_W,
        "splashW": SPLASH_W,
        "splashH": SPLASH_H,
        "dockYLoading": DOCK_Y_LOADING,
        "dockYReady": DOCK_Y_READY,
        "titleY": TITLE_Y,
        "subY": SUB_Y,
        "barW": BAR_W,
        "barH": BAR_H,
        "trackW": TRACK_W,
        "trackH": TRACK_H,
        "barTrackY": BAR_TRACK_Y,
        "tipY": TIP_Y,
    }
    lines = [
        "/** Auto-generated by tools/ui/generate_loading_screen_prefab.py — do not edit by hand. */",
        f"export const LOADING_SCREEN_PREFAB_UUID = '{prefab_uuid}';",
        "",
        "/** Prefab layout (design-space px). */",
        "export const LOADING_SCREEN_LAYOUT = {",
    ]
    for k, v in values.items():
        if isinstance(v, float):
            lines.append(f"    {k}: {round(v, 1)},")
        else:
            lines.append(f"    {k}: {v},")
    lines.append("} as const;")
    lines.append("")
    OUT_TS.write_text("\n".join(lines), encoding="utf-8")
    print("wrote", OUT_PREFAB, prefab_uuid)
    print("patched", OUT_TS)


if __name__ == "__main__":
    main()
