#!/usr/bin/env python3
"""Generate RewardPopup.prefab + RewardPopupFrames.ts — layout source of truth.

  /opt/homebrew/bin/python3.12 tools/ui/generate_reward_popup_prefab.py
"""
from __future__ import annotations

import json
import uuid
from pathlib import Path

from cocos_prefab_lib import CLOSE_SF, PrefabBuilder

ROOT = Path(__file__).resolve().parents[2]
OUT_PREFAB = ROOT / "assets/prefabs/ui/RewardPopup.prefab"
OUT_TS = ROOT / "assets/scripts/game/RewardPopupFrames.ts"

# --- Layout (panel-local, center origin) — mirrored in RewardPopupFrames.ts ---
PANEL_W, PANEL_H = 680, 500
PANEL_Y = 40
TITLE_Y = PANEL_H * 0.5 - 58
CHIPS_Y = 18
CHIPS_W, CHIPS_H = 600, 220
BTN_W, BTN_H = 280, 88
BTN_Y = -PANEL_H * 0.5 + 78
CLOSE_BTN, CLOSE_PAD = 84, 33
CLOSE_HIT = int(CLOSE_BTN * 1.85)
CLOSE_X = PANEL_W * 0.5 - CLOSE_PAD - CLOSE_BTN * 0.5
CLOSE_Y = PANEL_H * 0.5 - CLOSE_PAD - CLOSE_BTN * 0.5
COLS_MAX = 3
CHIP_W, CHIP_H = 160, 150
GAP_X, GAP_Y = 28, 20
ICON_ONE, ICON_MULTI = 96, 80
# Quest primary button face
BTN_PRIMARY_SF = "6f6c303c-496d-4ac5-9afb-ac4842fdb889@f9941"
INK = (62, 40, 22, 255)


def build() -> PrefabBuilder:
    b = PrefabBuilder("RewardPopup")
    root = b.node("RewardPopup", None, 0, 0, 1080, 1920, active=False)
    assert root == 1

    dim = b.node("Dimmer", root, 0, 0, 1200, 2200, with_graphics=True)
    panel = b.node("Panel", root, 0, PANEL_Y, PANEL_W, PANEL_H)
    chrome = b.node("Chrome", panel, 0, 0, PANEL_W, PANEL_H, with_graphics=True)

    title = b.node(
        "Title",
        panel,
        0,
        TITLE_Y,
        560,
        48,
        label={
            "text": "获得奖励",
            "size": 40,
            "color": INK,
            "h_align": 1,
            "outline": True,
        },
    )

    chips = b.node("Chips", panel, 0, CHIPS_Y, CHIPS_W, CHIPS_H)

    claim = b.node("ClaimBtn", panel, 0, BTN_Y, BTN_W, BTN_H)
    face = b.node("Face", claim, 0, 0, BTN_W, BTN_H, sprite=BTN_PRIMARY_SF)
    # Sliced button face
    for item in b.items:
        if isinstance(item, dict) and item.get("__type__") == "cc.Sprite" and item.get("node", {}).get("__id__") == face:
            item["_type"] = 1  # SLICED
            item["_sizeMode"] = 0
            item["_isTrimmedMode"] = False
    lab = b.node(
        "Lab",
        claim,
        0,
        2,
        BTN_W,
        BTN_H,
        label={
            "text": "领取",
            "size": 34,
            "color": (255, 252, 230, 255),
            "h_align": 1,
            "outline": True,
        },
    )
    b.set_children(claim, [face, lab])

    close = b.node("Close", panel, CLOSE_X, CLOSE_Y, CLOSE_HIT, CLOSE_HIT)
    close_icon = b.node("Icon", close, 0, 0, CLOSE_BTN, CLOSE_BTN, sprite=CLOSE_SF)
    b.set_children(close, [close_icon])

    b.set_children(panel, [chrome, title, chips, claim, close])
    b.set_children(root, [dim, panel])
    return b


def write_meta(path: Path, name: str, prefab_uuid: str) -> str:
    meta_path = Path(str(path) + ".meta")
    if meta_path.exists():
        prefab_uuid = json.loads(meta_path.read_text(encoding="utf-8")).get("uuid", prefab_uuid)
    meta = {
        "ver": "1.1.50",
        "importer": "prefab",
        "imported": True,
        "uuid": prefab_uuid,
        "files": [".json"],
        "subMetas": {},
        "userData": {"syncNodeName": name},
    }
    meta_path.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
    return prefab_uuid


def main():
    prefab_uuid = str(uuid.uuid4())
    meta_path = Path(str(OUT_PREFAB) + ".meta")
    if meta_path.exists():
        prefab_uuid = json.loads(meta_path.read_text(encoding="utf-8")).get("uuid", prefab_uuid)

    pb = build()
    OUT_PREFAB.parent.mkdir(parents=True, exist_ok=True)
    OUT_PREFAB.write_text(json.dumps(pb.items, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    prefab_uuid = write_meta(OUT_PREFAB, "RewardPopup", prefab_uuid)

    values = {
        "panelW": PANEL_W,
        "panelH": PANEL_H,
        "panelY": PANEL_Y,
        "titleY": TITLE_Y,
        "chipsY": CHIPS_Y,
        "chipsW": CHIPS_W,
        "chipsH": CHIPS_H,
        "btnW": BTN_W,
        "btnH": BTN_H,
        "btnY": BTN_Y,
        "closeX": CLOSE_X,
        "closeY": CLOSE_Y,
        "closeBtn": CLOSE_BTN,
        "closePad": CLOSE_PAD,
        "closeHit": CLOSE_HIT,
        "colsMax": COLS_MAX,
        "chipW": CHIP_W,
        "chipH": CHIP_H,
        "gapX": GAP_X,
        "gapY": GAP_Y,
        "iconOne": ICON_ONE,
        "iconMulti": ICON_MULTI,
    }
    lines = [
        "/** Auto-generated by tools/ui/generate_reward_popup_prefab.py — do not edit by hand. */",
        f"export const REWARD_POPUP_PREFAB_UUID = '{prefab_uuid}';",
        "",
        "/** Prefab layout (panel-local px). */",
        "export const REWARD_POPUP_LAYOUT = {",
    ]
    for k, v in values.items():
        if isinstance(v, float):
            lines.append(f"    {k}: {round(v, 1)},")
        else:
            lines.append(f"    {k}: {v},")
    lines.append("} as const;")
    lines.append("")
    OUT_TS.write_text("\n".join(lines), encoding="utf-8")
    print("wrote", OUT_PREFAB, prefab_uuid)
    print("patched", OUT_TS)


if __name__ == "__main__":
    main()
