#!/usr/bin/env python3
"""AI quest guide arrow → ui-quest-arrow.png (+ sync quest-marker).

  C:/Users/elex/scoop/apps/python310/current/python.exe tools/ui/process_quest_arrow_ai.py

Source: tools/ui/ai-source/quest-arrow-ai-ref.png
"""
from __future__ import print_function

import json
import uuid
from pathlib import Path

from PIL import Image

from process_bag_ai import (
    SF_SUFFIX,
    flood_corners,
    knock_gray_bg,
    pixelize,
    write_meta,
)

ROOT = Path(__file__).resolve().parents[2]
SRC = Path(__file__).resolve().parent / "ai-source" / "quest-arrow-ai-ref.png"
OUT = ROOT / "assets/textures/ui/ui-quest-arrow.png"
MARKER = ROOT / "assets/textures/ui/quest-marker.png"
UUID_MAP = Path(__file__).resolve().parent / "uuid-map.json"
QUEST_FRAMES = Path(__file__).resolve().parent / "quest-frames.json"
FARMER_FRAMES = Path(__file__).resolve().parent / "farmer-frames.json"
OUT_TS = ROOT / "assets/scripts/game/QuestFrames.ts"
OUT_FARMER_TS = ROOT / "assets/scripts/game/FarmerFrames.ts"

SIZE = 96
LOGICAL = 48
COLORS = 36

MARKER_SIZE = 48
MARKER_LOGICAL = 24


def patch_quest_frames(sf):
    data = {}
    if QUEST_FRAMES.exists():
        data = json.loads(QUEST_FRAMES.read_text(encoding="utf-8"))
    data["questArrow"] = {
        "spriteFrame": sf,
        "w": SIZE,
        "h": SIZE,
        "file": "ui-quest-arrow",
    }
    QUEST_FRAMES.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")

    layout_block = ""
    prefab_uuid = "80815e00-313f-4257-93fa-95aa89a25f45"
    if OUT_TS.exists():
        text = OUT_TS.read_text(encoding="utf-8")
        idx = text.find("export const QUEST_LAYOUT")
        if idx >= 0:
            layout_block = text[idx:]
        for line in text.splitlines():
            if "QUEST_PANEL_PREFAB_UUID" in line and "'" in line:
                prefab_uuid = line.split("'")[1]
                break

    lines = [
        "/** Auto-generated by tools/ui — do not edit by hand. */",
        "export const QUEST_FRAMES = {",
    ]
    for k, v in data.items():
        sfv = v["spriteFrame"] if isinstance(v, dict) else v
        lines.append("    {}: '{}',".format(k, sfv))
    lines.append("} as const;")
    lines.append("")
    lines.append("/** Prefab asset uuid — layout source of truth. */")
    lines.append("export const QUEST_PANEL_PREFAB_UUID = '{}';".format(prefab_uuid))
    lines.append("")
    if layout_block:
        lines.append(layout_block.rstrip())
        lines.append("")
    OUT_TS.write_text("\n".join(lines), encoding="utf-8")


def patch_farmer_quest_marker(sf):
    if not FARMER_FRAMES.exists():
        return
    data = json.loads(FARMER_FRAMES.read_text(encoding="utf-8"))
    data["questMarker"] = sf
    FARMER_FRAMES.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    if OUT_FARMER_TS.exists():
        text = OUT_FARMER_TS.read_text(encoding="utf-8")
        old = None
        for line in text.splitlines():
            if "questMarker:" in line:
                old = line
                break
        if old:
            new = "    questMarker: '{}',".format(sf)
            OUT_FARMER_TS.write_text(text.replace(old, new), encoding="utf-8")


def main():
    if not SRC.exists():
        raise SystemExit("missing {}".format(SRC))
    im = Image.open(SRC).convert("RGBA")
    im = knock_gray_bg(im)
    im = flood_corners(im)

    out = pixelize(im, LOGICAL, SIZE, COLORS)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    out.save(OUT)

    umap = {}
    if UUID_MAP.exists():
        umap = json.loads(UUID_MAP.read_text(encoding="utf-8"))
    image_uuid = write_meta(
        OUT,
        umap.get("ui-quest-arrow", {}).get("texture") or str(uuid.uuid4()),
        SIZE,
        SIZE,
        "ui-quest-arrow",
    )
    sf = "{}@{}".format(image_uuid, SF_SUFFIX)
    umap["ui-quest-arrow"] = {"texture": image_uuid, "spriteFrame": sf}

    # Keep world quest-marker in sync (smaller, same art; preserve UUID).
    marker = pixelize(im, MARKER_LOGICAL, MARKER_SIZE, COLORS)
    marker.save(MARKER)
    marker_uuid = write_meta(
        MARKER,
        umap.get("quest-marker", {}).get("texture")
        or "bf6dc369-932d-4921-bb95-ab64ac4a5362",
        MARKER_SIZE,
        MARKER_SIZE,
        "quest-marker",
    )
    marker_sf = "{}@{}".format(marker_uuid, SF_SUFFIX)
    umap["quest-marker"] = {"texture": marker_uuid, "spriteFrame": marker_sf}
    UUID_MAP.write_text(json.dumps(umap, indent=2) + "\n", encoding="utf-8")

    patch_quest_frames(sf)
    patch_farmer_quest_marker(marker_sf)

    print("OK", OUT.relative_to(ROOT), sf)
    print("OK", MARKER.relative_to(ROOT), marker_sf)


if __name__ == "__main__":
    main()
