#!/usr/bin/env python3
"""Soft starlight path dots → ui-quest-path-dot (+ twinkle frames).

Hand-pixel motes (no muddy AI halo). Optional AI ref only used if present
and after dark-fringe scrub; default is drawn.

  C:/Users/elex/scoop/apps/python310/current/python.exe tools/ui/process_quest_path_dot_ai.py
"""
from __future__ import print_function

import json
import uuid
from pathlib import Path

from PIL import Image

from process_bag_ai import SF_SUFFIX, write_meta

ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = ROOT / "assets/textures/ui"
UUID_MAP = Path(__file__).resolve().parent / "uuid-map.json"
QUEST_FRAMES = Path(__file__).resolve().parent / "quest-frames.json"
CATALOG = Path(__file__).resolve().parent / "catalog.json"
OUT_TS = ROOT / "assets/scripts/game/QuestFrames.ts"
PREVIEW = Path(__file__).resolve().parent / "ai-source" / "quest-path-dot-preview.png"

# Display size — small ground mote.
SIZE = 32
LOGICAL = 16
FRAME_COUNT = 4

# Warm fairy-dust palette — no dark outline (reads dirty on grass).
C_CORE = (255, 252, 230, 255)
C_HOT = (255, 236, 140, 255)
C_GOLD = (255, 214, 90, 230)
C_SOFT = (255, 228, 150, 140)
C_HALO = (255, 236, 180, 70)
C_MIST = (255, 244, 210, 36)


def upsert_catalog(cid, path, sf, size, note):
    data = json.loads(CATALOG.read_text(encoding="utf-8")) if CATALOG.exists() else {"assets": []}
    assets = data.get("assets") or []
    entry = {
        "id": cid,
        "kind": "ui",
        "spriteType": "simple",
        "designSize": [size, size],
        "path": path.replace("\\", "/"),
        "prefab": "",
        "note": note,
        "tags": ["ui", "quest", "guide", "path"],
        "spriteFrame": sf,
    }
    for i, a in enumerate(assets):
        if a.get("id") == cid:
            assets[i] = entry
            break
    else:
        assets.append(entry)
    data["assets"] = assets
    CATALOG.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def emit_quest_frames(entries):
    data = {}
    if QUEST_FRAMES.exists():
        data = json.loads(QUEST_FRAMES.read_text(encoding="utf-8"))
    data.update(entries)
    QUEST_FRAMES.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")

    layout_block = ""
    prefab_uuid = "80815e00-313f-4257-93fa-95aa89a25f45"
    if OUT_TS.exists():
        text = OUT_TS.read_text(encoding="utf-8")
        idx = text.find("export const QUEST_LAYOUT")
        if idx >= 0:
            layout_block = text[idx:]
        for line in text.splitlines():
            if "QUEST_PANEL_PREFAB_UUID" in line and "'" in line:
                prefab_uuid = line.split("'")[1]
                break

    lines = [
        "/** Auto-generated by tools/ui — do not edit by hand. */",
        "export const QUEST_FRAMES = {",
    ]
    for k, v in data.items():
        sfv = v["spriteFrame"] if isinstance(v, dict) else v
        lines.append("    {}: '{}',".format(k, sfv))
    lines.append("} as const;")
    lines.append("")
    lines.append("/** Prefab asset uuid — layout source of truth. */")
    lines.append("export const QUEST_PANEL_PREFAB_UUID = '{}';".format(prefab_uuid))
    lines.append("")
    if layout_block:
        lines.append(layout_block.rstrip())
        lines.append("")
    OUT_TS.write_text("\n".join(lines), encoding="utf-8")


def put(px, w, h, x, y, c):
    if 0 <= x < w and 0 <= y < h:
        r, g, b, a = c
        or_, og, ob, oa = px[x, y]
        if oa == 0:
            px[x, y] = c
            return
        # Soft over — keep brighter / more opaque on top.
        na = min(255, a + oa - (a * oa) // 255)
        if na <= 0:
            return
        nr = (r * a + or_ * (255 - a)) // 255
        ng = (g * a + og * (255 - a)) // 255
        nb = (b * a + ob * (255 - a)) // 255
        px[x, y] = (nr, ng, nb, na)


def disc(px, w, h, cx, cy, r, color):
    rr = r * r
    for y in range(cy - r, cy + r + 1):
        for x in range(cx - r, cx + r + 1):
            if (x - cx) * (x - cx) + (y - cy) * (y - cy) <= rr:
                put(px, w, h, x, y, color)


def cross(px, w, h, cx, cy, arm, tip_color, mid_color):
    for d in range(1, arm + 1):
        c = tip_color if d == arm else mid_color
        put(px, w, h, cx + d, cy, c)
        put(px, w, h, cx - d, cy, c)
        put(px, w, h, cx, cy + d, c)
        put(px, w, h, cx, cy - d, c)


def draw_mote(kind):
    """kind: soft | dim | spark | diamond"""
    im = Image.new("RGBA", (LOGICAL, LOGICAL), (0, 0, 0, 0))
    px = im.load()
    cx = cy = LOGICAL // 2  # 8

    if kind == "dim":
        disc(px, LOGICAL, LOGICAL, cx, cy, 3, C_MIST)
        disc(px, LOGICAL, LOGICAL, cx, cy, 2, C_HALO)
        disc(px, LOGICAL, LOGICAL, cx, cy, 1, C_SOFT)
        put(px, LOGICAL, LOGICAL, cx, cy, C_HOT)
        return im

    if kind == "spark":
        disc(px, LOGICAL, LOGICAL, cx, cy, 4, C_MIST)
        disc(px, LOGICAL, LOGICAL, cx, cy, 2, C_HALO)
        disc(px, LOGICAL, LOGICAL, cx, cy, 1, C_GOLD)
        put(px, LOGICAL, LOGICAL, cx, cy, C_CORE)
        cross(px, LOGICAL, LOGICAL, cx, cy, 4, C_SOFT, C_HOT)
        # Tiny diagonal glitter
        put(px, LOGICAL, LOGICAL, cx + 2, cy + 2, C_HALO)
        put(px, LOGICAL, LOGICAL, cx - 2, cy - 2, C_HALO)
        put(px, LOGICAL, LOGICAL, cx + 2, cy - 2, C_HALO)
        put(px, LOGICAL, LOGICAL, cx - 2, cy + 2, C_HALO)
        return im

    if kind == "diamond":
        disc(px, LOGICAL, LOGICAL, cx, cy, 3, C_MIST)
        for dx, dy in ((0, -2), (0, 2), (-2, 0), (2, 0), (0, -1), (0, 1), (-1, 0), (1, 0)):
            put(px, LOGICAL, LOGICAL, cx + dx, cy + dy, C_GOLD)
        put(px, LOGICAL, LOGICAL, cx, cy, C_CORE)
        put(px, LOGICAL, LOGICAL, cx + 1, cy, C_HOT)
        put(px, LOGICAL, LOGICAL, cx - 1, cy, C_HOT)
        put(px, LOGICAL, LOGICAL, cx, cy + 1, C_HOT)
        put(px, LOGICAL, LOGICAL, cx, cy - 1, C_HOT)
        return im

    # soft (default / main)
    disc(px, LOGICAL, LOGICAL, cx, cy, 4, C_MIST)
    disc(px, LOGICAL, LOGICAL, cx, cy, 3, C_HALO)
    disc(px, LOGICAL, LOGICAL, cx, cy, 2, C_SOFT)
    disc(px, LOGICAL, LOGICAL, cx, cy, 1, C_GOLD)
    put(px, LOGICAL, LOGICAL, cx, cy, C_CORE)
    # Tiny upright tick — reads as sparkle without heavy cross arms
    put(px, LOGICAL, LOGICAL, cx, cy - 3, C_HOT)
    put(px, LOGICAL, LOGICAL, cx, cy + 3, C_SOFT)
    put(px, LOGICAL, LOGICAL, cx - 3, cy, C_SOFT)
    put(px, LOGICAL, LOGICAL, cx + 3, cy, C_SOFT)
    return im


def upscale_nearest(im, out_size):
    return im.resize((out_size, out_size), Image.NEAREST)


def save_asset(im, name, umap):
    out = OUT_DIR / "{}.png".format(name)
    out.parent.mkdir(parents=True, exist_ok=True)
    pix = upscale_nearest(im, SIZE)
    pix.save(out)
    image_uuid = write_meta(
        out,
        umap.get(name, {}).get("texture") or str(uuid.uuid4()),
        SIZE,
        SIZE,
        name,
    )
    sf = "{}@{}".format(image_uuid, SF_SUFFIX)
    umap[name] = {"texture": image_uuid, "spriteFrame": sf}
    upsert_catalog(
        name,
        "assets/textures/ui/{}.png".format(name),
        sf,
        SIZE,
        "Quest ground path soft starlight (pixel)",
    )
    print("OK", out.relative_to(ROOT), sf)
    return sf, pix


def write_preview(frames):
    # Grass strip so we can judge muddy edges before play.
    pad = 8
    cell = SIZE + pad
    w = cell * len(frames) + pad
    h = SIZE + pad * 2 + 40
    prev = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    px = prev.load()
    for y in range(h):
        for x in range(w):
            g = 70 + (x * 3 + y * 5) % 36
            px[x, y] = (42 + g // 4, 110 + g // 2, 48 + g // 5, 255)
    for i, fr in enumerate(frames):
        prev.alpha_composite(fr, (pad + i * cell, pad))
    PREVIEW.parent.mkdir(parents=True, exist_ok=True)
    prev.save(PREVIEW)
    print("preview", PREVIEW.relative_to(ROOT))


def main():
    umap = {}
    if UUID_MAP.exists():
        umap = json.loads(UUID_MAP.read_text(encoding="utf-8"))

    kinds = ("soft", "dim", "spark", "diamond")
    logicals = [draw_mote(k) for k in kinds]
    frames = [upscale_nearest(m, SIZE) for m in logicals]
    write_preview(frames)

    entries = {}
    main_sf, _ = save_asset(logicals[0], "ui-quest-path-dot", umap)
    entries["questPathDot"] = {
        "spriteFrame": main_sf,
        "w": SIZE,
        "h": SIZE,
        "file": "ui-quest-path-dot",
    }
    for i, mote in enumerate(logicals):
        name = "ui-quest-path-dot-{}".format(i)
        sf, _ = save_asset(mote, name, umap)
        entries["questPathDot{}".format(i)] = {
            "spriteFrame": sf,
            "w": SIZE,
            "h": SIZE,
            "file": name,
        }

    UUID_MAP.write_text(json.dumps(umap, indent=2) + "\n", encoding="utf-8")
    emit_quest_frames(entries)
    print("quest path-dot frames patched")


if __name__ == "__main__":
    main()
