#!/usr/bin/env python3
"""AI walk-guide wisp → ui-quest-wisp (+ trail + idle frames).

Used by TutorialGuide when steering the player to walk somewhere.
Click prompts keep the yellow chevron (process_quest_arrow_ai.py / questArrow).

  C:/Users/elex/scoop/apps/python310/current/python.exe tools/ui/process_quest_wisp_ai.py

Sources:
  tools/ui/ai-source/quest-wisp-ai-ref.png
  tools/ui/ai-source/quest-wisp-sheet-ai-ref.png
  tools/ui/ai-source/quest-wisp-trail-ai-ref.png
"""
from __future__ import print_function

import json
import uuid
from pathlib import Path

from PIL import Image

from process_bag_ai import (
    SF_SUFFIX,
    flood_corners,
    knock_gray_bg,
    pixelize,
    write_meta,
)

ROOT = Path(__file__).resolve().parents[2]
AI = Path(__file__).resolve().parent / "ai-source"
OUT_DIR = ROOT / "assets/textures/ui"
UUID_MAP = Path(__file__).resolve().parent / "uuid-map.json"
QUEST_FRAMES = Path(__file__).resolve().parent / "quest-frames.json"
CATALOG = Path(__file__).resolve().parent / "catalog.json"
OUT_TS = ROOT / "assets/scripts/game/QuestFrames.ts"
FARMER_FRAMES = Path(__file__).resolve().parent / "farmer-frames.json"
OUT_FARMER_TS = ROOT / "assets/scripts/game/FarmerFrames.ts"
MARKER = OUT_DIR / "quest-marker.png"

SRC_MAIN = AI / "quest-wisp-ai-ref.png"
SRC_SHEET = AI / "quest-wisp-sheet-ai-ref.png"
SRC_TRAIL = AI / "quest-wisp-trail-ai-ref.png"

SIZE = 96
LOGICAL = 48
COLORS = 40
MARKER_SIZE = 48
MARKER_LOGICAL = 24
FRAME_COUNT = 4


def upsert_catalog(cid, path, sf, size, note):
    data = json.loads(CATALOG.read_text(encoding="utf-8")) if CATALOG.exists() else {"assets": []}
    assets = data.get("assets") or []
    entry = {
        "id": cid,
        "kind": "ui",
        "spriteType": "simple",
        "designSize": [size, size],
        "path": path.replace("\\", "/"),
        "prefab": "",
        "note": note,
        "tags": ["ui", "quest", "guide"],
        "spriteFrame": sf,
    }
    for i, a in enumerate(assets):
        if a.get("id") == cid:
            assets[i] = entry
            break
    else:
        assets.append(entry)
    data["assets"] = assets
    CATALOG.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def emit_quest_frames(entries):
    data = {}
    if QUEST_FRAMES.exists():
        data = json.loads(QUEST_FRAMES.read_text(encoding="utf-8"))
    data.update(entries)
    QUEST_FRAMES.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")

    layout_block = ""
    prefab_uuid = "80815e00-313f-4257-93fa-95aa89a25f45"
    if OUT_TS.exists():
        text = OUT_TS.read_text(encoding="utf-8")
        idx = text.find("export const QUEST_LAYOUT")
        if idx >= 0:
            layout_block = text[idx:]
        for line in text.splitlines():
            if "QUEST_PANEL_PREFAB_UUID" in line and "'" in line:
                prefab_uuid = line.split("'")[1]
                break

    lines = [
        "/** Auto-generated by tools/ui — do not edit by hand. */",
        "export const QUEST_FRAMES = {",
    ]
    for k, v in data.items():
        sfv = v["spriteFrame"] if isinstance(v, dict) else v
        lines.append("    {}: '{}',".format(k, sfv))
    lines.append("} as const;")
    lines.append("")
    lines.append("/** Prefab asset uuid — layout source of truth. */")
    lines.append("export const QUEST_PANEL_PREFAB_UUID = '{}';".format(prefab_uuid))
    lines.append("")
    if layout_block:
        lines.append(layout_block.rstrip())
        lines.append("")
    OUT_TS.write_text("\n".join(lines), encoding="utf-8")


def patch_farmer_quest_marker(sf):
    if not FARMER_FRAMES.exists():
        return
    data = json.loads(FARMER_FRAMES.read_text(encoding="utf-8"))
    data["questMarker"] = sf
    FARMER_FRAMES.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    if OUT_FARMER_TS.exists():
        text = OUT_FARMER_TS.read_text(encoding="utf-8")
        old = None
        for line in text.splitlines():
            if "questMarker:" in line:
                old = line
                break
        if old:
            new = "    questMarker: '{}',".format(sf)
            OUT_FARMER_TS.write_text(text.replace(old, new), encoding="utf-8")


def save_asset(im, name, umap, logical=LOGICAL, size=SIZE, colors=COLORS):
    out = OUT_DIR / "{}.png".format(name)
    out.parent.mkdir(parents=True, exist_ok=True)
    pix = pixelize(im, logical, size, colors)
    pix.save(out)
    image_uuid = write_meta(
        out,
        umap.get(name, {}).get("texture") or str(uuid.uuid4()),
        size,
        size,
        name,
    )
    sf = "{}@{}".format(image_uuid, SF_SUFFIX)
    umap[name] = {"texture": image_uuid, "spriteFrame": sf}
    upsert_catalog(
        name,
        "assets/textures/ui/{}.png".format(name),
        sf,
        size,
        "Quest guide wisp (AI)",
    )
    print("OK", out.relative_to(ROOT), sf)
    return sf, pix


def prep(src):
    im = Image.open(src).convert("RGBA")
    im = knock_gray_bg(im)
    im = flood_corners(im)
    return im


def slice_sheet(src, count=FRAME_COUNT):
    im = prep(src)
    w, h = im.size
    cell_w = w // count
    # Detect content rows — sheet is a single horizontal strip.
    frames = []
    for i in range(count):
        cell = im.crop((i * cell_w, 0, (i + 1) * cell_w, h))
        frames.append(cell)
    return frames


def main():
    for p in (SRC_MAIN, SRC_SHEET, SRC_TRAIL):
        if not p.exists():
            raise SystemExit("missing {}".format(p))

    umap = {}
    if UUID_MAP.exists():
        umap = json.loads(UUID_MAP.read_text(encoding="utf-8"))

    entries = {}

    # Walk-direction cue (TutorialGuide). Click prompts keep questArrow / yellow chevron.
    main_sf, _main_pix = save_asset(prep(SRC_MAIN), "ui-quest-wisp", umap)
    entries["questWisp"] = {
        "spriteFrame": main_sf,
        "w": SIZE,
        "h": SIZE,
        "file": "ui-quest-wisp",
    }

    # Idle pulse frames from sheet.
    for i, cell in enumerate(slice_sheet(SRC_SHEET)):
        name = "ui-quest-wisp-{}".format(i)
        sf, _ = save_asset(cell, name, umap)
        entries["questWisp{}".format(i)] = {
            "spriteFrame": sf,
            "w": SIZE,
            "h": SIZE,
            "file": name,
        }

    # Edge trail (default art points east / +X).
    trail_sf, _ = save_asset(prep(SRC_TRAIL), "ui-quest-wisp-trail", umap)
    entries["questWispTrail"] = {
        "spriteFrame": trail_sf,
        "w": SIZE,
        "h": SIZE,
        "file": "ui-quest-wisp-trail",
    }

    # Smaller world quest-marker stays in sync.
    marker = pixelize(prep(SRC_MAIN), MARKER_LOGICAL, MARKER_SIZE, COLORS)
    marker.save(MARKER)
    marker_uuid = write_meta(
        MARKER,
        umap.get("quest-marker", {}).get("texture")
        or "bf6dc369-932d-4921-bb95-ab64ac4a5362",
        MARKER_SIZE,
        MARKER_SIZE,
        "quest-marker",
    )
    marker_sf = "{}@{}".format(marker_uuid, SF_SUFFIX)
    umap["quest-marker"] = {"texture": marker_uuid, "spriteFrame": marker_sf}
    print("OK", MARKER.relative_to(ROOT), marker_sf)

    UUID_MAP.write_text(json.dumps(umap, indent=2) + "\n", encoding="utf-8")
    emit_quest_frames(entries)
    patch_farmer_quest_marker(marker_sf)
    print("quest frames patched")


if __name__ == "__main__":
    main()
