#!/usr/bin/env python3
"""AI quest HUD badge → ui-quest-btn.png (same plate language as ui-bag-btn).

  C:/Users/elex/scoop/apps/python310/current/python.exe tools/ui/process_quest_btn_ai.py

Source: tools/ui/ai-source/quest-btn-ai-ref.png
Keeps existing .meta UUID via uuid-map / meta file.
"""
from __future__ import print_function

import json
import uuid
from pathlib import Path

from PIL import Image

from process_bag_ai import (
    SF_SUFFIX,
    flood_corners,
    knock_gray_bg,
    pixelize,
    write_meta,
)

ROOT = Path(__file__).resolve().parents[2]
SRC = Path(__file__).resolve().parent / "ai-source" / "quest-btn-ai-ref.png"
OUT = ROOT / "assets/textures/ui/ui-quest-btn.png"
UUID_MAP = Path(__file__).resolve().parent / "uuid-map.json"
QUEST_FRAMES = Path(__file__).resolve().parent / "quest-frames.json"
OUT_TS = ROOT / "assets/scripts/game/QuestFrames.ts"

SIZE = 96
LOGICAL = 48
COLORS = 40


def patch_quest_frames(sf):
    data = {}
    if QUEST_FRAMES.exists():
        data = json.loads(QUEST_FRAMES.read_text(encoding="utf-8"))
    data["questBtn"] = {"spriteFrame": sf, "w": SIZE, "h": SIZE, "file": "ui-quest-btn"}
    QUEST_FRAMES.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")

    layout_block = ""
    prefab_uuid = "80815e00-313f-4257-93fa-95aa89a25f45"
    if OUT_TS.exists():
        text = OUT_TS.read_text(encoding="utf-8")
        idx = text.find("export const QUEST_LAYOUT")
        if idx >= 0:
            layout_block = text[idx:]
        for line in text.splitlines():
            if "QUEST_PANEL_PREFAB_UUID" in line and "'" in line:
                prefab_uuid = line.split("'")[1]
                break

    lines = [
        "/** Auto-generated by tools/ui — do not edit by hand. */",
        "export const QUEST_FRAMES = {",
    ]
    for k, v in data.items():
        sfv = v["spriteFrame"] if isinstance(v, dict) else v
        lines.append("    {}: '{}',".format(k, sfv))
    lines.append("} as const;")
    lines.append("")
    lines.append("/** Prefab asset uuid — layout source of truth. */")
    lines.append("export const QUEST_PANEL_PREFAB_UUID = '{}';".format(prefab_uuid))
    lines.append("")
    if layout_block:
        lines.append(layout_block.rstrip())
        lines.append("")
    OUT_TS.write_text("\n".join(lines), encoding="utf-8")


def main():
    if not SRC.exists():
        raise SystemExit("missing {}".format(SRC))
    im = Image.open(SRC).convert("RGBA")
    im = knock_gray_bg(im)
    im = flood_corners(im)
    out = pixelize(im, LOGICAL, SIZE, COLORS)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    out.save(OUT)

    umap = {}
    if UUID_MAP.exists():
        umap = json.loads(UUID_MAP.read_text(encoding="utf-8"))
    image_uuid = write_meta(
        OUT,
        umap.get("ui-quest-btn", {}).get("texture") or str(uuid.uuid4()),
        SIZE,
        SIZE,
        "ui-quest-btn",
    )
    sf = "{}@{}".format(image_uuid, SF_SUFFIX)
    umap["ui-quest-btn"] = {"texture": image_uuid, "spriteFrame": sf}
    UUID_MAP.write_text(json.dumps(umap, indent=2) + "\n", encoding="utf-8")
    patch_quest_frames(sf)
    print("OK", OUT.relative_to(ROOT), sf)


if __name__ == "__main__":
    main()
