/** Auto-generated by tools/ui/generate_dialogue_panel_prefab.py — do not edit by hand. */
export const DIALOGUE_PANEL_PREFAB_UUID = '096c7715-7993-4328-99dc-a78bbd693f41';

/** Prefab layout (box-local px). */
export const DIALOGUE_PANEL_LAYOUT = {
    boxW: 1000,
    boxH: 260,
    boxY: -780,
    avatar: 96,
    avatarFrame: 108,
    namePlateW: 220,
    namePlateH: 48,
    nameStackX: -370.0,
    nameY: 132.0,
    portraitY: 218.0,
    bodyYSpeaker: 78,
    bodyYNarration: 96,
    bodyW: 900,
    hintX: 382.0,
    hintY: -60.0,
    arrowY: 16,
} as const;
