/** Auto-generated by tools/ui/generate_fishing_minigame_prefab.py — do not edit by hand. */
export const FISHING_MINIGAME_PREFAB_UUID = 'f216d5b6-ca8e-402e-bef9-c568b843cfe7';

/** Prefab layout (canvas-local px). */
export const FISHING_MINIGAME_LAYOUT = {
    panelW: 160,
    panelH: 584,
    panelX: -200,
    panelY: 24,
    trackW: 56,
    trackH: 536,
    trackX: -9,
    trackY: 1,
    progW: 16,
    progX: 41,
    fishSize: 32,
    barInsetX: 3,
    holdR: 96,
    holdX: 240,
    holdY: -40,
    bannerY: 352.0,
} as const;
