/** Auto-generated by tools/ui/generate_gm_panel_prefab.py — do not edit by hand. */
export const GM_PANEL_PREFAB_UUID = 'b9523ab7-7d89-4599-ac62-7b94016c20d0';
export const GM_CHIP_PREFAB_UUID = 'ab5a436a-a964-43b9-88b9-c528fbcb449a';

/** Prefab layout (panel-local / canvas-local px). */
export const GM_PANEL_LAYOUT = {
    panelW: 960,
    panelH: 1580,
    panelY: 10,
    contentW: 888,
    titleY: 636.5,
    tabY: 568.5,
    tabW: 109,
    tabH: 56,
    tabGap: 10,
    pagesW: 888,
    pagesH: 1243,
    pagesY: -108.5,
    hintY: -758.0,
    closeX: 382.0,
    closeY: 692.0,
    closeBtn: 84,
    closePad: 56,
    closeHit: 155,
    chipW: 72,
    chipH: 44,
    chipX: -492,
    chipY: 904,
} as const;

export const GM_TAB_IDS = ['time', 'item', 'quest', 'qtest', 'system'] as const;
