/** Auto-generated by tools/ui/generate_loading_screen_prefab.py — do not edit by hand. */
export const LOADING_SCREEN_PREFAB_UUID = '7647ec39-2458-438f-830f-9d1039367cc1';

/** Prefab layout (design-space px). */
export const LOADING_SCREEN_LAYOUT = {
    designW: 1080,
    splashW: 1080,
    splashH: 2200,
    dockYLoading: -880,
    dockYReady: -640,
    titleY: 820,
    subY: 740,
    barW: 720,
    barH: 32,
    trackW: 734,
    trackH: 46,
    barTrackY: 24,
    tipY: -30,
} as const;
