import {
    _decorator,
    assetManager,
    Color,
    Component,
    Graphics,
    Label,
    Node,
    Prefab,
    Sprite,
    SpriteFrame,
    UIOpacity,
    UITransform,
    instantiate,
    view,
} from 'cc';
import { CQuest } from '../cfg/schema';
import { InputBridge } from './InputBridge';
import { MATERIAL_FRAMES } from './MaterialFrames';
import { QUEST_FRAMES, QUEST_LAYOUT, QUEST_PANEL_PREFAB_UUID } from './QuestFrames';
import { QuestSystem } from './QuestSystem';
import { TOOL_FRAMES } from './ToolFrames';
import { applyUiFont, loadUiFont, styleUiLabel } from './UiFont';

const { ccclass, property } = _decorator;

type FrameKey = keyof typeof QUEST_FRAMES;
const L = QUEST_LAYOUT;

/**
 * Quest journal — layout lives in `assets/prefabs/ui/QuestPanel.prefab`
 * (generated by tools/ui/generate_quest_panel_prefab.py).
 * Tracker chip stays runtime-built on Canvas.
 */
@ccclass('QuestPanel')
export class QuestPanel extends Component {
    quests: QuestSystem | null = null;

    @property(Node)
    panelRoot: Node | null = null;

    @property(Node)
    dimmer: Node | null = null;

    @property(Label)
    titleLab: Label | null = null;

    @property(Node)
    heroNode: Node | null = null;

    @property(Sprite)
    heroIcon: Sprite | null = null;

    @property(Label)
    heroTitleLab: Label | null = null;

    @property(Label)
    heroDescLab: Label | null = null;

    @property(Label)
    heroProgLab: Label | null = null;

    @property(Node)
    heroBarNode: Node | null = null;

    @property(Label)
    sectionLab: Label | null = null;

    @property(Node)
    listHost: Node | null = null;

    @property(Node)
    btnClose: Node | null = null;

    @property(Node)
    btnGoto: Node | null = null;

    private _tracker: Node | null = null;
    private _trackerTitle: Label | null = null;
    private _trackerProg: Label | null = null;
    private _trackerBar: Graphics | null = null;
    private _prefabRoot: Node | null = null;
    private _open = false;
    private _prevBlocking = false;
    private _frames = new Map<FrameKey, SpriteFrame>();
    private _iconCache = new Map<string, SpriteFrame>();
    private _framesReady = false;
    private _heroBar: Graphics | null = null;
    private _mounted = false;

    onLoad() {
        this.loadFrames(() => {
            this.buildTracker();
            this.refreshTracker();
        });
        // Prefab may already be on this.node (editor) or we mount at runtime.
        if (this.panelRoot) {
            this._mounted = true;
            this._prefabRoot = this.node;
            this.node.active = false;
            this.paintHeroChrome();
            this.paintDimmer();
        }
        loadUiFont().then((font) => {
            if (!font) return;
            for (const lab of [
                this._trackerTitle,
                this._trackerProg,
                this.titleLab,
                this.heroTitleLab,
                this.heroDescLab,
                this.heroProgLab,
                this.sectionLab,
            ]) {
                if (lab) applyUiFont(lab);
            }
        });
    }

    onDestroy() {
        if (this._open) InputBridge.uiBlocking = this._prevBlocking;
        this._tracker?.destroy();
        if (this._prefabRoot && this._prefabRoot !== this.node) {
            this._prefabRoot.destroy();
        }
    }

    /** Bootstrap: mount prefab under Canvas when script is on Canvas. */
    ensureMounted(done?: () => void) {
        if (this._mounted || this.panelRoot) {
            this._mounted = true;
            done?.();
            return;
        }
        assetManager.loadAny({ uuid: QUEST_PANEL_PREFAB_UUID }, (err, asset) => {
            if (err || !asset) {
                console.warn('[QuestPanel] prefab missing', err);
                done?.();
                return;
            }
            const canvas = this.node;
            const old = canvas.getChildByName('QuestPanel');
            if (old) old.destroy();
            const inst = instantiate(asset as Prefab);
            inst.name = 'QuestPanel';
            inst.layer = canvas.layer;
            inst.setParent(canvas);
            inst.setSiblingIndex(canvas.children.length - 1);
            inst.active = false;
            this._prefabRoot = inst;
            this.resolveRefs(inst);
            this._mounted = true;
            this.paintHeroChrome();
            this.paintDimmer();
            done?.();
        });
    }

    bind(quests: QuestSystem) {
        this.quests = quests;
        quests.onChange(() => {
            this.refreshTracker();
            if (this._open) this.refreshPanel();
        });
        this.refreshTracker();
    }

    get isOpen(): boolean {
        return this._open;
    }

    toggle() {
        this.setOpen(!this._open);
    }

    setOpen(open: boolean) {
        if (open === this._open) {
            if (open) this.refreshPanel();
            return;
        }
        const apply = () => {
            this._open = open;
            if (open) {
                this._prevBlocking = InputBridge.uiBlocking;
                InputBridge.uiBlocking = true;
                InputBridge.clear();
                if (this._prefabRoot) this._prefabRoot.active = true;
                this.refreshPanel();
            } else {
                InputBridge.uiBlocking = this._prevBlocking;
                if (this._prefabRoot) this._prefabRoot.active = false;
            }
        };
        if (open && !this._mounted) {
            this.ensureMounted(() => {
                if (this._framesReady) apply();
                else this.loadFrames(apply);
            });
            return;
        }
        if (open && !this._framesReady) {
            this.loadFrames(apply);
            return;
        }
        apply();
    }

    handleTap(uiX: number, uiY: number): boolean {
        if (!this._open) {
            if (this.hitTracker(uiX, uiY)) {
                this.setOpen(true);
                return true;
            }
            return false;
        }
        const local = this.uiToCanvasLocal(uiX, uiY);
        if (this.hitNodeWorld(this.btnClose, local.x, local.y)) {
            this.setOpen(false);
            return true;
        }
        if (this.hitNodeWorld(this.btnGoto, local.x, local.y)) {
            this.quests?.runGoto();
            this.setOpen(false);
            return true;
        }
        return true;
    }

    private resolveRefs(root: Node) {
        this.panelRoot = root.getChildByName('Panel');
        this.dimmer = root.getChildByName('Dim');
        const panel = this.panelRoot;
        if (!panel) return;
        this.titleLab = panel.getChildByName('Title')?.getComponent(Label) ?? null;
        this.heroNode = panel.getChildByName('Hero');
        this.heroIcon = this.heroNode?.getChildByName('HeroIcon')?.getComponent(Sprite) ?? null;
        this.heroTitleLab = this.heroNode?.getChildByName('HeroTitle')?.getComponent(Label) ?? null;
        this.heroDescLab = this.heroNode?.getChildByName('HeroDesc')?.getComponent(Label) ?? null;
        this.heroProgLab = this.heroNode?.getChildByName('HeroProg')?.getComponent(Label) ?? null;
        this.heroBarNode = this.heroNode?.getChildByName('HeroBar') ?? null;
        this.sectionLab = panel.getChildByName('Section')?.getComponent(Label) ?? null;
        this.listHost = panel.getChildByName('List');
        this.btnClose = panel.getChildByName('BtnClose');
        this.btnGoto = panel.getChildByName('BtnGoto');
    }

    private loadFrames(done?: () => void) {
        const keys = Object.keys(QUEST_FRAMES) as FrameKey[];
        let left = keys.length;
        for (const key of keys) {
            assetManager.loadAny({ uuid: QUEST_FRAMES[key] }, (err, asset) => {
                if (!err && asset) this._frames.set(key, asset as SpriteFrame);
                left--;
                if (left <= 0) {
                    this._framesReady = true;
                    done?.();
                }
            });
        }
    }

    private paintDimmer() {
        if (!this.dimmer) return;
        let g = this.dimmer.getComponent(Graphics);
        if (!g) g = this.dimmer.addComponent(Graphics);
        const vis = view.getVisibleSize();
        g.clear();
        g.fillColor = new Color(12, 16, 20, 150);
        g.rect(-vis.width, -vis.height, vis.width * 2, vis.height * 2);
        g.fill();
    }

    private paintHeroChrome() {
        if (!this.heroNode) return;
        let g = this.heroNode.getComponent(Graphics);
        if (!g) g = this.heroNode.addComponent(Graphics);
        const w = L.heroW;
        const h = L.heroH;
        g.clear();
        // Parchment plate — no stretched leaf row art.
        g.fillColor = new Color(236, 214, 168, 255);
        g.roundRect(-w * 0.5, -h * 0.5, w, h, 14);
        g.fill();
        g.strokeColor = new Color(176, 120, 52, 255);
        g.lineWidth = 4;
        g.roundRect(-w * 0.5, -h * 0.5, w, h, 14);
        g.stroke();
        g.strokeColor = new Color(90, 56, 28, 255);
        g.lineWidth = 2;
        g.roundRect(-w * 0.5 + 5, -h * 0.5 + 5, w - 10, h - 10, 10);
        g.stroke();
        // Corner studs
        for (const [sx, sy] of [
            [-w * 0.5 + 14, h * 0.5 - 14],
            [w * 0.5 - 14, h * 0.5 - 14],
            [-w * 0.5 + 14, -h * 0.5 + 14],
            [w * 0.5 - 14, -h * 0.5 + 14],
        ] as [number, number][]) {
            g.fillColor = new Color(232, 186, 72, 255);
            g.circle(sx, sy, 5);
            g.fill();
            g.fillColor = new Color(90, 56, 28, 255);
            g.circle(sx, sy, 2);
            g.fill();
        }
        this._heroBar = this.heroBarNode?.getComponent(Graphics) ?? null;
        if (this.heroBarNode && !this._heroBar) {
            this._heroBar = this.heroBarNode.addComponent(Graphics);
        }
    }

    private refreshTracker() {
        if (!this._trackerTitle || !this._trackerProg) return;
        const q = this.quests?.activeQuest;
        if (!q || this.quests?.isFinished) {
            this._trackerTitle.string = '旅途日志';
            this._trackerProg.string = this.quests?.isFinished ? '主线已完成' : '加载中…';
            this.paintBar(this._trackerBar, 0, 220, 8);
            return;
        }
        const prog = this.quests!.progressOf(q);
        this._trackerTitle.string = q.name;
        this._trackerProg.string = `${prog.desc}  ${prog.current}/${prog.target}`;
        this.paintBar(this._trackerBar, prog.target ? prog.current / prog.target : 0, 220, 8);
    }

    private refreshPanel() {
        if (!this.listHost || !this.quests) return;
        const q = this.quests.activeQuest;

        if (this.heroTitleLab && this.heroDescLab && this.heroProgLab) {
            if (!q || this.quests.isFinished) {
                this.heroTitleLab.string = this.quests.isFinished ? '旅途告一段落' : '加载中…';
                this.heroDescLab.string = this.quests.isFinished
                    ? '主线指引已完成，去院子里自由探索吧。'
                    : '正在读取任务配置…';
                this.heroProgLab.string = '';
                this.paintBar(this._heroBar, 1, L.heroW - 48, 12);
                if (this.heroIcon) this.heroIcon.spriteFrame = null;
            } else {
                const prog = this.quests.progressOf(q);
                this.heroTitleLab.string = q.name;
                this.heroDescLab.string = q.desc;
                this.heroProgLab.string = `${prog.current}/${prog.target}`;
                this.paintBar(this._heroBar, prog.target ? prog.current / prog.target : 0, L.heroW - 48, 12);
                const uuid = this.iconUuidFor(q);
                if (uuid && this.heroIcon) this.loadIcon(uuid, this.heroIcon);
            }
            applyUiFont(this.heroTitleLab);
            applyUiFont(this.heroDescLab);
            applyUiFont(this.heroProgLab);
        }

        this.listHost.removeAllChildren();
        const quests = this.quests.allQuests();
        const activeId = q?.id ?? -1;
        const n = quests.length;
        const totalH = n * L.rowH + Math.max(0, n - 1) * L.rowGap;
        let y = totalH * 0.5 - L.rowH * 0.5;
        for (const quest of quests) {
            this.addQuestRow(
                this.listHost,
                quest,
                quest.id === activeId,
                this.quests.isCompleted(quest.id),
                y,
            );
            y -= L.rowH + L.rowGap;
        }
    }

    private addQuestRow(host: Node, q: CQuest, active: boolean, done: boolean, y: number) {
        const row = new Node(`Q_${q.id}`);
        row.layer = host.layer;
        row.setParent(host);
        row.setPosition(0, y, 0);
        row.addComponent(UITransform).setContentSize(L.rowW, L.rowH);

        const frame: FrameKey = done ? 'rowDone' : active ? 'rowActive' : 'row';
        const bg = new Node('Bg');
        bg.layer = host.layer;
        bg.setParent(row);
        bg.addComponent(UITransform).setContentSize(L.rowW, L.rowH);
        const sp = bg.addComponent(Sprite);
        sp.sizeMode = Sprite.SizeMode.CUSTOM;
        const sf = this._frames.get(frame);
        if (sf) sp.spriteFrame = sf;

        if (!active && !done) {
            const op = row.addComponent(UIOpacity);
            op.opacity = 220;
        }

        // Icon — vertically centered, fixed left column
        const iconX = -L.rowW * 0.5 + 36;
        const iconUuid = this.iconUuidFor(q);
        if (iconUuid) {
            const iconN = new Node('Icon');
            iconN.layer = host.layer;
            iconN.setParent(row);
            iconN.setPosition(iconX, 0, 0);
            iconN.addComponent(UITransform).setContentSize(L.icon, L.icon);
            const isp = iconN.addComponent(Sprite);
            isp.sizeMode = Sprite.SizeMode.CUSTOM;
            this.loadIcon(iconUuid, isp);
        }

        // Title — left-anchored text column
        const textLeft = -L.rowW * 0.5 + 68;
        const textW = L.rowW - 160;
        const nameN = new Node('Name');
        nameN.layer = host.layer;
        nameN.setParent(row);
        nameN.setPosition(textLeft, 8, 0);
        const nameUt = nameN.addComponent(UITransform);
        nameUt.setContentSize(textW, 26);
        nameUt.setAnchorPoint(0, 0.5);
        const name = nameN.addComponent(Label);
        name.string = q.name;
        name.horizontalAlign = Label.HorizontalAlign.LEFT;
        name.verticalAlign = Label.VerticalAlign.CENTER;
        styleUiLabel(name, {
            size: 20,
            color: done
                ? new Color(60, 90, 48, 255)
                : active
                  ? new Color(68, 40, 18, 255)
                  : new Color(255, 232, 190, 255),
            outline: !done && !active,
            outlineWidth: 2,
            outlineColor: new Color(40, 24, 12, 220),
        });
        applyUiFont(name);

        // Status / progress — right column, vertically centered
        const statusN = new Node('Status');
        statusN.layer = host.layer;
        statusN.setParent(row);
        statusN.setPosition(L.rowW * 0.5 - 16, 0, 0);
        const stUt = statusN.addComponent(UITransform);
        stUt.setContentSize(100, 28);
        stUt.setAnchorPoint(1, 0.5);
        const status = statusN.addComponent(Label);
        if (done) status.string = '完成';
        else if (active && this.quests) {
            const p = this.quests.progressOf(q);
            status.string = `${p.current}/${p.target}`;
        } else status.string = '';
        status.horizontalAlign = Label.HorizontalAlign.RIGHT;
        status.verticalAlign = Label.VerticalAlign.CENTER;
        styleUiLabel(status, {
            size: 18,
            color: done
                ? new Color(60, 90, 48, 255)
                : active
                  ? new Color(120, 72, 28, 255)
                  : new Color(200, 170, 120, 200),
            outline: false,
        });
        applyUiFont(status);

        // Subline only for active (below title, still inside row)
        if (active && this.quests) {
            const p = this.quests.progressOf(q);
            const subN = new Node('Sub');
            subN.layer = host.layer;
            subN.setParent(row);
            subN.setPosition(textLeft, -12, 0);
            const subUt = subN.addComponent(UITransform);
            subUt.setContentSize(textW, 20);
            subUt.setAnchorPoint(0, 0.5);
            const sub = subN.addComponent(Label);
            sub.string = p.desc;
            sub.horizontalAlign = Label.HorizontalAlign.LEFT;
            styleUiLabel(sub, {
                size: 14,
                color: new Color(110, 78, 42, 255),
                outline: false,
            });
            applyUiFont(sub);
        }
    }

    private buildTracker() {
        const canvas = this.node;
        const old = canvas.getChildByName('QuestTracker');
        if (old) old.destroy();

        const tw = 420;
        const th = 78;
        const bar = new Node('QuestTracker');
        bar.layer = canvas.layer;
        bar.setParent(canvas);
        const { halfW, halfH } = this.canvasHalf();
        bar.setPosition(-halfW + tw * 0.5 + 16, halfH - 200, 0);
        bar.addComponent(UITransform).setContentSize(tw, th);
        const sp = bar.addComponent(Sprite);
        sp.sizeMode = Sprite.SizeMode.CUSTOM;
        const sf = this._frames.get('tracker');
        if (sf) sp.spriteFrame = sf;

        const textLeft = -tw * 0.5 + 70;
        const textW = tw - 90;

        const titleN = new Node('Title');
        titleN.layer = canvas.layer;
        titleN.setParent(bar);
        titleN.setPosition(textLeft, 14, 0);
        const tUt = titleN.addComponent(UITransform);
        tUt.setContentSize(textW, 24);
        tUt.setAnchorPoint(0, 0.5);
        const title = titleN.addComponent(Label);
        title.horizontalAlign = Label.HorizontalAlign.LEFT;
        styleUiLabel(title, { size: 20, color: new Color(72, 44, 22, 255), outline: false });
        this._trackerTitle = title;

        const progN = new Node('Prog');
        progN.layer = canvas.layer;
        progN.setParent(bar);
        progN.setPosition(textLeft, -4, 0);
        const pUt = progN.addComponent(UITransform);
        pUt.setContentSize(textW, 20);
        pUt.setAnchorPoint(0, 0.5);
        const prog = progN.addComponent(Label);
        prog.horizontalAlign = Label.HorizontalAlign.LEFT;
        styleUiLabel(prog, { size: 15, color: new Color(110, 78, 42, 255), outline: false });
        this._trackerProg = prog;

        const barN = new Node('Bar');
        barN.layer = canvas.layer;
        barN.setParent(bar);
        barN.setPosition(textLeft + 110, -24, 0);
        barN.addComponent(UITransform).setContentSize(220, 10);
        this._trackerBar = barN.addComponent(Graphics);

        this._tracker = bar;
        applyUiFont(title);
        applyUiFont(prog);
    }

    private iconUuidFor(q: CQuest): string | null {
        const p = (q.param || '').toLowerCase();
        if (p === 'grass' || q.id === 1001) return MATERIAL_FRAMES.grass ?? null;
        if (p === 'wood') return MATERIAL_FRAMES.wood ?? null;
        if (p === 'dirt') return MATERIAL_FRAMES.dirt ?? null;
        if (p === 'stone') return MATERIAL_FRAMES.stone ?? null;
        if (p === 'fish' || q.id === 1007) return MATERIAL_FRAMES.fish ?? null;
        if (p.includes('seed') || q.id === 1003 || q.id === 1004) return TOOL_FRAMES.seeds ?? null;
        if (q.id === 1002) return TOOL_FRAMES.hoe ?? null;
        if (q.id === 1005) return TOOL_FRAMES.can ?? null;
        if (q.id === 1006) return TOOL_FRAMES.hand ?? null;
        return null;
    }

    private loadIcon(uuid: string, sp: Sprite) {
        const cached = this._iconCache.get(uuid);
        if (cached) {
            sp.spriteFrame = cached;
            return;
        }
        assetManager.loadAny({ uuid }, (err, asset) => {
            if (err || !asset || !sp.isValid) return;
            const sf = asset as SpriteFrame;
            this._iconCache.set(uuid, sf);
            sp.spriteFrame = sf;
        });
    }

    private paintBar(g: Graphics | null, ratio: number, w: number, h: number) {
        if (!g?.isValid) return;
        g.clear();
        const x0 = -w * 0.5;
        const y0 = -h * 0.5;
        g.fillColor = new Color(70, 48, 28, 180);
        g.roundRect(x0, y0, w, h, h * 0.45);
        g.fill();
        const fillW = Math.max(0, Math.min(1, ratio)) * (w - 4);
        if (fillW > 1) {
            g.fillColor = new Color(110, 180, 70, 255);
            g.roundRect(x0 + 2, y0 + 2, fillW, h - 4, (h - 4) * 0.45);
            g.fill();
        }
    }

    private hitTracker(uiX: number, uiY: number): boolean {
        if (!this._tracker?.isValid) return false;
        const local = this.uiToCanvasLocal(uiX, uiY);
        const ui = this._tracker.getComponent(UITransform);
        if (!ui) return false;
        const p = this._tracker.position;
        const hw = ui.contentSize.width * 0.5;
        const hh = ui.contentSize.height * 0.5;
        return Math.abs(local.x - p.x) <= hw && Math.abs(local.y - p.y) <= hh;
    }

    private hitNodeWorld(node: Node | null, lx: number, ly: number): boolean {
        if (!node?.isValid || !node.active || !this.panelRoot || !this._prefabRoot) return false;
        const ui = node.getComponent(UITransform);
        if (!ui) return false;
        // prefabRoot at (0,0), panel at panel.position, btn at btn.position
        const px = this.panelRoot.position.x + node.position.x;
        const py = this.panelRoot.position.y + node.position.y;
        const hw = ui.contentSize.width * 0.5 + 8;
        const hh = ui.contentSize.height * 0.5 + 8;
        return lx >= px - hw && lx <= px + hw && ly >= py - hh && ly <= py + hh;
    }

    private uiToCanvasLocal(uiX: number, uiY: number) {
        const { halfW, halfH } = this.canvasHalf();
        return { x: uiX - halfW, y: uiY - halfH };
    }

    private canvasHalf() {
        const ui = this.node.getComponent(UITransform);
        const vis = view.getVisibleSize();
        return {
            halfW: (ui?.contentSize.width || vis.width) * 0.5,
            halfH: (ui?.contentSize.height || vis.height) * 0.5,
        };
    }
}
