/** Auto-generated by tools/ui/generate_quest_tracker_prefab.py — do not edit by hand. */
export const QUEST_TRACKER_PREFAB_UUID = '20264ac2-c06e-47ab-9d75-3f7d838538d6';

/** Prefab layout (canvas-local px). */
export const QUEST_TRACKER_LAYOUT = {
    barW: 420,
    barH: 120,
    barX: -314.0,
    dockY: -682.0,
    edgePad: 16,
    titleY: 18,
    rowY: -22,
    textLeft: -186.0,
    textRight: 186.0,
    objW: 262,
    countW: 100,
} as const;
