/** Auto-generated by tools/ui — do not edit by hand. */
export const QUEST_FRAMES = {
    panel: 'a2ff1daa-0b00-47a1-8b82-1fee6b0c2ea6@f9941',
    tracker: 'f9e5c175-643d-4b93-8934-537b20f9103e@f9941',
    rowActive: '71d50bba-50d0-4e78-a1ae-8d30c8061ba3@f9941',
    row: 'c67602bb-d56c-46ea-a17c-8fb674595c03@f9941',
    rowDone: '788cfe35-3a07-4b1a-bd2e-4d6991cf407c@f9941',
    btnSecondary: '69b6a8f8-7068-4fc7-8de3-26b3d3a715e9@f9941',
    btnPrimary: '6f6c303c-496d-4ac5-9afb-ac4842fdb889@f9941',
    questBtn: 'e639ab24-7c1a-46ba-93a4-688ca1c1ab08@f9941',
    questArrow: '74358256-5fdf-4193-a127-53998d13c454@f9941',
} as const;

/** Prefab asset uuid — layout source of truth. */
export const QUEST_PANEL_PREFAB_UUID = '80815e00-313f-4257-93fa-95aa89a25f45';

export const QUEST_LAYOUT = {
    panelW: 700,
    panelH: 1120,
    contentW: 632,
    rowW: 632,
    rowH: 152,
    rowGap: 14,
    listY: -47.0,
    listH: 900,
    titleY: 479.1,
    closeX: 275.0,
    closeY: 485.0,
    closeBtn: 84,
    icon: 44,
} as const;
