/** Auto-generated by tools/ui/generate_reward_popup_prefab.py — do not edit by hand. */
export const REWARD_POPUP_PREFAB_UUID = '81d5d825-4109-46ec-a0dc-f8f5715230bc';

/** Prefab layout (panel-local px). */
export const REWARD_POPUP_LAYOUT = {
    panelW: 680,
    panelH: 500,
    panelY: 40,
    titleY: 192.0,
    chipsY: 18,
    chipsW: 600,
    chipsH: 220,
    btnW: 280,
    btnH: 88,
    btnY: -172.0,
    closeX: 265.0,
    closeY: 175.0,
    closeBtn: 84,
    closePad: 33,
    closeHit: 155,
    colsMax: 3,
    chipW: 160,
    chipH: 150,
    gapX: 28,
    gapY: 20,
    iconOne: 96,
    iconMulti: 80,
} as const;
