/** Auto-generated by tools/ui/generate_stick_visual_prefab.py — do not edit by hand. */
export const STICK_VISUAL_PREFAB_UUID = '052ce99b-f42c-498c-80e0-7ac1d19b84bb';

/** Prefab layout (canvas-local px). */
export const STICK_VISUAL_LAYOUT = {
    visual: 180,
    base: 160,
    knob: 80,
    restX: 0,
    restY: -600,
    radius: 80,
} as const;
