/** Auto-generated by tools/ui/generate_story_intro_panel_prefab.py — do not edit by hand. */
export const STORY_INTRO_PANEL_PREFAB_UUID = '35cee20a-3c8c-4cbf-8b7c-673d1bb73993';

/** Prefab layout (design-space px). */
export const STORY_INTRO_PANEL_LAYOUT = {
    designW: 1080,
    designH: 1920,
    boxW: 1000,
    boxH: 260,
    boxY: -780,
    bodyY: 96,
    bodyW: 900,
    hintX: 382.0,
    hintY: -60.0,
    arrowY: 16,
    artW: 720,
    artH: 1080,
    artY: 180,
    skipW: 148,
    skipH: 56,
    skipPad: 36,
    skipX: 430.0,
    skipY: 896.0,
} as const;
