/** Auto-generated by tools/ui/generate_town_shop_prefab.py — do not edit by hand. */
export const TOWN_SHOP_PREFAB_UUID = 'f7abdbd2-e42c-4fb3-8485-587ce6b076d4';
export const TOWN_SHOP_ROW_PREFAB_UUID = 'cd550fd7-77f6-4f20-b03f-ef3190a13454';

/** Prefab layout (panel-local px). */
export const TOWN_SHOP_LAYOUT = {
    panelW: 720,
    panelH: 980,
    panelY: 40,
    rowW: 640,
    rowH: 92,
    rowGap: 8,
    listTop: 242.0,
    listY: -18.0,
    listH: 520,
    titleY: 426.0,
    goldY: 372.0,
    tabY: 312.0,
    tabH: 48,
    tabW: 180,
    hintY: -322.0,
    actionY: -402.0,
    actionW: 320,
    actionH: 72,
    qtyBtn: 56,
    qtyY: -402.0,
    minusX: -250,
    plusX: -90,
    qtyLabX: -170,
    confirmX: 160,
    confirmW: 300,
    closeX: 285.0,
    closeY: 415.0,
    closeBtn: 84,
    closePad: 33,
    closeHit: 155,
} as const;
