/** Auto-generated by tools/ui/generate_tutorial_guide_prefab.py — do not edit by hand. */
export const TUTORIAL_GUIDE_PREFAB_UUID = '67a8d83a-cf80-4cad-b012-6939429786c5';

/** Prefab layout (canvas-local px). */
export const TUTORIAL_GUIDE_LAYOUT = {
    tipW: 560,
    tipH: 64,
    finger: 96,
    dragGhost: 72,
    clickLabW: 80,
    clickLabH: 48,
    clickLabY: 92.0,
} as const;
