/*
 * AUTO-GENERATED by story-editor from story graph {{STORY_ID}}.
 * Do not edit manually — re-export from the story editor.
 */
import { Node, Vec3 } from 'cc';
import { AbsStory } from '../AbsStory';

export class {{CLASS_NAME}} extends AbsStory {
    public readonly storyId = {{STORY_ID}};
{{FIELDS}}
{{LIFECYCLE_METHODS}}
{{BLUEPRINT_METHODS}}
}
