import * as fs from 'fs';
import { listLocalStories } from '../browseStories';
import { writeFsText } from '../assetIo';
import { CLASS_PREFIX, classMapFsPath, ensureDir, generatedClassFsPath, generatedDirFs } from '../paths';

export function regenerateClassMap(): { ok: boolean; count: number; path: string } {
  ensureDir(generatedDirFs());
  const items = listLocalStories().filter(
    (s) => s.exportFlag && fs.existsSync(generatedClassFsPath(s.storyId))
  );

  const imports: string[] = [];
  const entries: string[] = [];

  for (const s of items) {
    const cls = `${CLASS_PREFIX}${s.storyId}`;
    imports.push(`import { ${cls} } from './${cls}';`);
    entries.push(`  ${s.storyId}: () => new ${cls}(),`);
  }

  const code = `/*
 * AUTO-GENERATED by story-editor. Do not edit manually.
 */
import type { AbsStory } from '../AbsStory';
${imports.join('\n')}

const MAP: Record<number, () => AbsStory> = {
${entries.join('\n')}
};

export function createTsStory(storyId: number): AbsStory | null {
  const factory = MAP[storyId | 0];
  return factory ? factory() : null;
}

export function listExportedStoryIds(): number[] {
  return Object.keys(MAP).map((k) => Number(k));
}
`;

  const out = classMapFsPath();
  writeFsText(out, code);
  return { ok: true, count: items.length, path: out };
}
